/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/fetch-client.ts";
import type {
	GetHealthQueryResponse,
	PostAuthLoginMutationRequest,
	PostAuthLoginMutationResponse,
	GetAuthGithubQueryResponse,
	GetAuthGithubCallbackQueryResponse,
	GetAuthGithubCallbackQueryParams,
	GetAuthValidateQueryResponse,
	PostAuthLogoutMutationResponse,
	GetAuthVerifyEmailQueryResponse,
	GetAuthVerifyEmailQueryParams,
	PostAuthResendVerificationMutationRequest,
	PostAuthResendVerificationMutationResponse,
	PostUsersMutationRequest,
	PostUsersMutationResponse,
	GetUsersQueryResponse,
	PutUsersMutationRequest,
	PutUsersMutationResponse,
	DeleteUsersMutationResponse,
	GetUsersUseridQueryResponse,
	GetUsersUseridPathParams,
	PostProjectsMutationRequest,
	PostProjectsMutationResponse,
	GetProjectsQueryResponse,
	GetProjectsQueryParams,
	GetProjectsProjectidQueryResponse,
	GetProjectsProjectidPathParams,
	PutProjectsProjectidMutationRequest,
	PutProjectsProjectidMutationResponse,
	PutProjectsProjectidPathParams,
	DeleteProjectsProjectidMutationResponse,
	DeleteProjectsProjectidPathParams,
	PostProjectsProjectidRepositoryMutationRequest,
	PostProjectsProjectidRepositoryMutationResponse,
	PostProjectsProjectidRepositoryPathParams,
	GetProjectsProjectidParticipantsQueryResponse,
	GetProjectsProjectidParticipantsPathParams,
	PostProjectsProjectidParticipantsMutationRequest,
	PostProjectsProjectidParticipantsMutationResponse,
	PostProjectsProjectidParticipantsPathParams,
	PutProjectsProjectidParticipantsUseridRoleMutationRequest,
	PutProjectsProjectidParticipantsUseridRoleMutationResponse,
	PutProjectsProjectidParticipantsUseridRolePathParams,
	DeleteProjectsProjectidParticipantsUseridMutationResponse,
	DeleteProjectsProjectidParticipantsUseridPathParams,
	GetGithubRepositoriesQueryResponse,
	PostSprintsMutationRequest,
	PostSprintsMutationResponse,
	GetSprintsSprintidQueryResponse,
	GetSprintsSprintidPathParams,
	PutSprintsSprintidMutationRequest,
	PutSprintsSprintidMutationResponse,
	PutSprintsSprintidPathParams,
	DeleteSprintsSprintidMutationResponse,
	DeleteSprintsSprintidPathParams,
	GetSprintsProjectProjectidQueryResponse,
	GetSprintsProjectProjectidPathParams,
	GetSprintsProjectProjectidActiveQueryResponse,
	GetSprintsProjectProjectidActivePathParams,
	GetSprintsSprintidKanbanQueryResponse,
	GetSprintsSprintidKanbanPathParams,
	PutSprintsSprintidActivateMutationResponse,
	PutSprintsSprintidActivatePathParams,
	PutSprintsSprintidCompleteMutationResponse,
	PutSprintsSprintidCompletePathParams,
	PostDocumentsMutationRequest,
	PostDocumentsMutationResponse,
	GetDocumentsQueryResponse,
	GetDocumentsDocumentidQueryResponse,
	GetDocumentsDocumentidPathParams,
	PutDocumentsDocumentidMutationRequest,
	PutDocumentsDocumentidMutationResponse,
	PutDocumentsDocumentidPathParams,
	DeleteDocumentsDocumentidMutationResponse,
	DeleteDocumentsDocumentidPathParams,
	GetDocumentsProjectProjectidQueryResponse,
	GetDocumentsProjectProjectidPathParams,
	GetColumnsColumnidQueryResponse,
	GetColumnsColumnidPathParams,
	GetColumnsSprintSprintidQueryResponse,
	GetColumnsSprintSprintidPathParams,
	PostCardsMutationRequest,
	PostCardsMutationResponse,
	GetCardsCardidQueryResponse,
	GetCardsCardidPathParams,
	PutCardsCardidMutationRequest,
	PutCardsCardidMutationResponse,
	PutCardsCardidPathParams,
	DeleteCardsCardidMutationResponse,
	DeleteCardsCardidPathParams,
	GetCardsColumnColumnidQueryResponse,
	GetCardsColumnColumnidPathParams,
	GetCardsProjectProjectidQueryResponse,
	GetCardsProjectProjectidPathParams,
	GetCardsSprintSprintidQueryResponse,
	GetCardsSprintSprintidPathParams,
	PutCardsCardidMoveMutationRequest,
	PutCardsCardidMoveMutationResponse,
	PutCardsCardidMovePathParams,
	PostTagsMutationRequest,
	PostTagsMutationResponse,
	GetTagsTagidQueryResponse,
	GetTagsTagidPathParams,
	PutTagsTagidMutationRequest,
	PutTagsTagidMutationResponse,
	PutTagsTagidPathParams,
	DeleteTagsTagidMutationResponse,
	DeleteTagsTagidPathParams,
	GetTagsProjectProjectidQueryResponse,
	GetTagsProjectProjectidPathParams,
	GetTagsCardCardidQueryResponse,
	GetTagsCardCardidPathParams,
	PostTagsAssignMutationRequest,
	PostTagsAssignMutationResponse,
	DeleteTagsTagidCardCardidMutationResponse,
	DeleteTagsTagidCardCardidPathParams,
} from "./models.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/fetch-client.ts";

function getGetHealthUrl() {
	const res = { method: "GET", url: `http://localhost:8080/health` as const };
	return res;
}

/**
 * {@link /health}
 */
export async function getHealth(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetHealthQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({ method: "GET", url: getGetHealthUrl().url.toString(), ...requestConfig });
	return res;
}

function getPostAuthLoginUrl() {
	const res = {
		method: "POST",
		url: `http://localhost:8080/auth/login` as const,
	};
	return res;
}

/**
 * {@link /auth/login}
 */
export async function postAuthLogin(
	data: PostAuthLoginMutationRequest,
	config: Partial<RequestConfig<PostAuthLoginMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PostAuthLoginMutationResponse,
		ResponseErrorConfig<Error>,
		PostAuthLoginMutationRequest
	>({
		method: "POST",
		url: getPostAuthLoginUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getGetAuthGithubUrl() {
	const res = {
		method: "GET",
		url: `http://localhost:8080/auth/github` as const,
	};
	return res;
}

/**
 * @description Get GitHub OAuth authorization URL
 * {@link /auth/github}
 */
export async function getAuthGithub(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetAuthGithubQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetAuthGithubUrl().url.toString(),
		...requestConfig,
	});
	return res;
}

function getGetAuthGithubCallbackUrl() {
	const res = {
		method: "GET",
		url: `http://localhost:8080/auth/github/callback` as const,
	};
	return res;
}

/**
 * @description Handle GitHub OAuth callback
 * {@link /auth/github/callback}
 */
export async function getAuthGithubCallback(
	params: GetAuthGithubCallbackQueryParams,
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetAuthGithubCallbackQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetAuthGithubCallbackUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res;
}

function getGetAuthValidateUrl() {
	const res = {
		method: "GET",
		url: `http://localhost:8080/auth/validate` as const,
	};
	return res;
}

/**
 * @description Validate user authentication
 * {@link /auth/validate}
 */
export async function getAuthValidate(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetAuthValidateQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetAuthValidateUrl().url.toString(),
		...requestConfig,
	});
	return res;
}

function getPostAuthLogoutUrl() {
	const res = {
		method: "POST",
		url: `http://localhost:8080/auth/logout` as const,
	};
	return res;
}

/**
 * @description Logout current session
 * {@link /auth/logout}
 */
export async function postAuthLogout(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		PostAuthLogoutMutationResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "POST",
		url: getPostAuthLogoutUrl().url.toString(),
		...requestConfig,
	});
	return res;
}

function getGetAuthVerifyEmailUrl() {
	const res = {
		method: "GET",
		url: `http://localhost:8080/auth/verify-email` as const,
	};
	return res;
}

/**
 * @description Verify email address
 * {@link /auth/verify-email}
 */
export async function getAuthVerifyEmail(
	params: GetAuthVerifyEmailQueryParams,
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetAuthVerifyEmailQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetAuthVerifyEmailUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res;
}

function getPostAuthResendVerificationUrl() {
	const res = {
		method: "POST",
		url: `http://localhost:8080/auth/resend-verification` as const,
	};
	return res;
}

/**
 * @description Resend verification email
 * {@link /auth/resend-verification}
 */
export async function postAuthResendVerification(
	data: PostAuthResendVerificationMutationRequest,
	config: Partial<RequestConfig<PostAuthResendVerificationMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PostAuthResendVerificationMutationResponse,
		ResponseErrorConfig<Error>,
		PostAuthResendVerificationMutationRequest
	>({
		method: "POST",
		url: getPostAuthResendVerificationUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getPostUsersUrl() {
	const res = { method: "POST", url: `http://localhost:8080/users` as const };
	return res;
}

/**
 * @description Create
 * {@link /users}
 */
export async function postUsers(
	data: PostUsersMutationRequest,
	config: Partial<RequestConfig<PostUsersMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PostUsersMutationResponse,
		ResponseErrorConfig<Error>,
		PostUsersMutationRequest
	>({
		method: "POST",
		url: getPostUsersUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getGetUsersUrl() {
	const res = { method: "GET", url: `http://localhost:8080/users` as const };
	return res;
}

/**
 * @description List all users
 * {@link /users}
 */
export async function getUsers(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetUsersQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({ method: "GET", url: getGetUsersUrl().url.toString(), ...requestConfig });
	return res;
}

function getPutUsersUrl() {
	const res = { method: "PUT", url: `http://localhost:8080/users` as const };
	return res;
}

/**
 * @description Update user
 * {@link /users}
 */
export async function putUsers(
	data?: PutUsersMutationRequest,
	config: Partial<RequestConfig<PutUsersMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PutUsersMutationResponse,
		ResponseErrorConfig<Error>,
		PutUsersMutationRequest
	>({
		method: "PUT",
		url: getPutUsersUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getDeleteUsersUrl() {
	const res = { method: "DELETE", url: `http://localhost:8080/users` as const };
	return res;
}

/**
 * @description Delete user
 * {@link /users}
 */
export async function deleteUsers(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		DeleteUsersMutationResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "DELETE",
		url: getDeleteUsersUrl().url.toString(),
		...requestConfig,
	});
	return res;
}

function getGetUsersUseridUrl(userId: GetUsersUseridPathParams["userId"]) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/users/${userId}` as const,
	};
	return res;
}

/**
 * @description Get user by ID
 * {@link /users/:userId}
 */
export async function getUsersUserid(
	userId: GetUsersUseridPathParams["userId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetUsersUseridQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetUsersUseridUrl(userId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getPostProjectsUrl() {
	const res = {
		method: "POST",
		url: `http://localhost:8080/projects` as const,
	};
	return res;
}

/**
 * @description Create a new project
 * {@link /projects}
 */
export async function postProjects(
	data: PostProjectsMutationRequest,
	config: Partial<RequestConfig<PostProjectsMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PostProjectsMutationResponse,
		ResponseErrorConfig<Error>,
		PostProjectsMutationRequest
	>({
		method: "POST",
		url: getPostProjectsUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getGetProjectsUrl() {
	const res = { method: "GET", url: `http://localhost:8080/projects` as const };
	return res;
}

/**
 * @description List user projects with participants. Optionally filter by status (active, archived, or draft).
 * {@link /projects}
 */
export async function getProjects(
	params?: GetProjectsQueryParams,
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetProjectsQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetProjectsUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res;
}

function getGetProjectsProjectidUrl(
	projectId: GetProjectsProjectidPathParams["projectId"],
) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/projects/${projectId}` as const,
	};
	return res;
}

/**
 * @description Get project by ID with participants
 * {@link /projects/:projectId}
 */
export async function getProjectsProjectid(
	projectId: GetProjectsProjectidPathParams["projectId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetProjectsProjectidQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetProjectsProjectidUrl(projectId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getPutProjectsProjectidUrl(
	projectId: PutProjectsProjectidPathParams["projectId"],
) {
	const res = {
		method: "PUT",
		url: `http://localhost:8080/projects/${projectId}` as const,
	};
	return res;
}

/**
 * @description Update project
 * {@link /projects/:projectId}
 */
export async function putProjectsProjectid(
	projectId: PutProjectsProjectidPathParams["projectId"],
	data?: PutProjectsProjectidMutationRequest,
	config: Partial<RequestConfig<PutProjectsProjectidMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PutProjectsProjectidMutationResponse,
		ResponseErrorConfig<Error>,
		PutProjectsProjectidMutationRequest
	>({
		method: "PUT",
		url: getPutProjectsProjectidUrl(projectId).url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getDeleteProjectsProjectidUrl(
	projectId: DeleteProjectsProjectidPathParams["projectId"],
) {
	const res = {
		method: "DELETE",
		url: `http://localhost:8080/projects/${projectId}` as const,
	};
	return res;
}

/**
 * @description Delete project
 * {@link /projects/:projectId}
 */
export async function deleteProjectsProjectid(
	projectId: DeleteProjectsProjectidPathParams["projectId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		DeleteProjectsProjectidMutationResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "DELETE",
		url: getDeleteProjectsProjectidUrl(projectId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getPostProjectsProjectidRepositoryUrl(
	projectId: PostProjectsProjectidRepositoryPathParams["projectId"],
) {
	const res = {
		method: "POST",
		url: `http://localhost:8080/projects/${projectId}/repository` as const,
	};
	return res;
}

/**
 * @description Link a GitHub repository to a project
 * {@link /projects/:projectId/repository}
 */
export async function postProjectsProjectidRepository(
	projectId: PostProjectsProjectidRepositoryPathParams["projectId"],
	data: PostProjectsProjectidRepositoryMutationRequest,
	config: Partial<
		RequestConfig<PostProjectsProjectidRepositoryMutationRequest>
	> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PostProjectsProjectidRepositoryMutationResponse,
		ResponseErrorConfig<Error>,
		PostProjectsProjectidRepositoryMutationRequest
	>({
		method: "POST",
		url: getPostProjectsProjectidRepositoryUrl(projectId).url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getGetProjectsProjectidParticipantsUrl(
	projectId: GetProjectsProjectidParticipantsPathParams["projectId"],
) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/projects/${projectId}/participants` as const,
	};
	return res;
}

/**
 * @description List participants for a project
 * {@link /projects/:projectId/participants}
 */
export async function getProjectsProjectidParticipants(
	projectId: GetProjectsProjectidParticipantsPathParams["projectId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetProjectsProjectidParticipantsQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetProjectsProjectidParticipantsUrl(projectId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getPostProjectsProjectidParticipantsUrl(
	projectId: PostProjectsProjectidParticipantsPathParams["projectId"],
) {
	const res = {
		method: "POST",
		url: `http://localhost:8080/projects/${projectId}/participants` as const,
	};
	return res;
}

/**
 * @description Add a participant to a project
 * {@link /projects/:projectId/participants}
 */
export async function postProjectsProjectidParticipants(
	projectId: PostProjectsProjectidParticipantsPathParams["projectId"],
	data: PostProjectsProjectidParticipantsMutationRequest,
	config: Partial<
		RequestConfig<PostProjectsProjectidParticipantsMutationRequest>
	> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PostProjectsProjectidParticipantsMutationResponse,
		ResponseErrorConfig<Error>,
		PostProjectsProjectidParticipantsMutationRequest
	>({
		method: "POST",
		url: getPostProjectsProjectidParticipantsUrl(projectId).url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getPutProjectsProjectidParticipantsUseridRoleUrl(
	projectId: PutProjectsProjectidParticipantsUseridRolePathParams["projectId"],
	userId: PutProjectsProjectidParticipantsUseridRolePathParams["userId"],
) {
	const res = {
		method: "PUT",
		url: `http://localhost:8080/projects/${projectId}/participants/${userId}/role` as const,
	};
	return res;
}

/**
 * @description Update a participant role
 * {@link /projects/:projectId/participants/:userId/role}
 */
export async function putProjectsProjectidParticipantsUseridRole(
	projectId: PutProjectsProjectidParticipantsUseridRolePathParams["projectId"],
	userId: PutProjectsProjectidParticipantsUseridRolePathParams["userId"],
	data: PutProjectsProjectidParticipantsUseridRoleMutationRequest,
	config: Partial<
		RequestConfig<PutProjectsProjectidParticipantsUseridRoleMutationRequest>
	> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PutProjectsProjectidParticipantsUseridRoleMutationResponse,
		ResponseErrorConfig<Error>,
		PutProjectsProjectidParticipantsUseridRoleMutationRequest
	>({
		method: "PUT",
		url: getPutProjectsProjectidParticipantsUseridRoleUrl(
			projectId,
			userId,
		).url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getDeleteProjectsProjectidParticipantsUseridUrl(
	projectId: DeleteProjectsProjectidParticipantsUseridPathParams["projectId"],
	userId: DeleteProjectsProjectidParticipantsUseridPathParams["userId"],
) {
	const res = {
		method: "DELETE",
		url: `http://localhost:8080/projects/${projectId}/participants/${userId}` as const,
	};
	return res;
}

/**
 * @description Remove a participant from a project
 * {@link /projects/:projectId/participants/:userId}
 */
export async function deleteProjectsProjectidParticipantsUserid(
	projectId: DeleteProjectsProjectidParticipantsUseridPathParams["projectId"],
	userId: DeleteProjectsProjectidParticipantsUseridPathParams["userId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		DeleteProjectsProjectidParticipantsUseridMutationResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "DELETE",
		url: getDeleteProjectsProjectidParticipantsUseridUrl(
			projectId,
			userId,
		).url.toString(),
		...requestConfig,
	});
	return res;
}

function getGetGithubRepositoriesUrl() {
	const res = {
		method: "GET",
		url: `http://localhost:8080/github/repositories` as const,
	};
	return res;
}

/**
 * @description Get all GitHub repositories for authenticated user
 * {@link /github/repositories}
 */
export async function getGithubRepositories(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetGithubRepositoriesQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetGithubRepositoriesUrl().url.toString(),
		...requestConfig,
	});
	return res;
}

function getPostSprintsUrl() {
	const res = { method: "POST", url: `http://localhost:8080/sprints` as const };
	return res;
}

/**
 * @description Create a new sprint
 * {@link /sprints}
 */
export async function postSprints(
	data: PostSprintsMutationRequest,
	config: Partial<RequestConfig<PostSprintsMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PostSprintsMutationResponse,
		ResponseErrorConfig<Error>,
		PostSprintsMutationRequest
	>({
		method: "POST",
		url: getPostSprintsUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getGetSprintsSprintidUrl(
	sprintId: GetSprintsSprintidPathParams["sprintId"],
) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/sprints/${sprintId}` as const,
	};
	return res;
}

/**
 * @description Get sprint by ID
 * {@link /sprints/:sprintId}
 */
export async function getSprintsSprintid(
	sprintId: GetSprintsSprintidPathParams["sprintId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetSprintsSprintidQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetSprintsSprintidUrl(sprintId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getPutSprintsSprintidUrl(
	sprintId: PutSprintsSprintidPathParams["sprintId"],
) {
	const res = {
		method: "PUT",
		url: `http://localhost:8080/sprints/${sprintId}` as const,
	};
	return res;
}

/**
 * @description Update sprint
 * {@link /sprints/:sprintId}
 */
export async function putSprintsSprintid(
	sprintId: PutSprintsSprintidPathParams["sprintId"],
	data?: PutSprintsSprintidMutationRequest,
	config: Partial<RequestConfig<PutSprintsSprintidMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PutSprintsSprintidMutationResponse,
		ResponseErrorConfig<Error>,
		PutSprintsSprintidMutationRequest
	>({
		method: "PUT",
		url: getPutSprintsSprintidUrl(sprintId).url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getDeleteSprintsSprintidUrl(
	sprintId: DeleteSprintsSprintidPathParams["sprintId"],
) {
	const res = {
		method: "DELETE",
		url: `http://localhost:8080/sprints/${sprintId}` as const,
	};
	return res;
}

/**
 * @description Delete sprint
 * {@link /sprints/:sprintId}
 */
export async function deleteSprintsSprintid(
	sprintId: DeleteSprintsSprintidPathParams["sprintId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		DeleteSprintsSprintidMutationResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "DELETE",
		url: getDeleteSprintsSprintidUrl(sprintId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getGetSprintsProjectProjectidUrl(
	projectId: GetSprintsProjectProjectidPathParams["projectId"],
) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/sprints/project/${projectId}` as const,
	};
	return res;
}

/**
 * @description List sprints by project ID
 * {@link /sprints/project/:projectId}
 */
export async function getSprintsProjectProjectid(
	projectId: GetSprintsProjectProjectidPathParams["projectId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetSprintsProjectProjectidQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetSprintsProjectProjectidUrl(projectId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getGetSprintsProjectProjectidActiveUrl(
	projectId: GetSprintsProjectProjectidActivePathParams["projectId"],
) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/sprints/project/${projectId}/active` as const,
	};
	return res;
}

/**
 * @description Get active sprint by project ID
 * {@link /sprints/project/:projectId/active}
 */
export async function getSprintsProjectProjectidActive(
	projectId: GetSprintsProjectProjectidActivePathParams["projectId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetSprintsProjectProjectidActiveQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetSprintsProjectProjectidActiveUrl(projectId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getGetSprintsSprintidKanbanUrl(
	sprintId: GetSprintsSprintidKanbanPathParams["sprintId"],
) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/sprints/${sprintId}/kanban` as const,
	};
	return res;
}

/**
 * @description Get sprint kanban board with columns, cards and tags
 * {@link /sprints/:sprintId/kanban}
 */
export async function getSprintsSprintidKanban(
	sprintId: GetSprintsSprintidKanbanPathParams["sprintId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetSprintsSprintidKanbanQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetSprintsSprintidKanbanUrl(sprintId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getPutSprintsSprintidActivateUrl(
	sprintId: PutSprintsSprintidActivatePathParams["sprintId"],
) {
	const res = {
		method: "PUT",
		url: `http://localhost:8080/sprints/${sprintId}/activate` as const,
	};
	return res;
}

/**
 * @description Activate sprint
 * {@link /sprints/:sprintId/activate}
 */
export async function putSprintsSprintidActivate(
	sprintId: PutSprintsSprintidActivatePathParams["sprintId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		PutSprintsSprintidActivateMutationResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "PUT",
		url: getPutSprintsSprintidActivateUrl(sprintId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getPutSprintsSprintidCompleteUrl(
	sprintId: PutSprintsSprintidCompletePathParams["sprintId"],
) {
	const res = {
		method: "PUT",
		url: `http://localhost:8080/sprints/${sprintId}/complete` as const,
	};
	return res;
}

/**
 * @description Complete sprint
 * {@link /sprints/:sprintId/complete}
 */
export async function putSprintsSprintidComplete(
	sprintId: PutSprintsSprintidCompletePathParams["sprintId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		PutSprintsSprintidCompleteMutationResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "PUT",
		url: getPutSprintsSprintidCompleteUrl(sprintId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getPostDocumentsUrl() {
	const res = {
		method: "POST",
		url: `http://localhost:8080/documents` as const,
	};
	return res;
}

/**
 * @description Create a new document
 * {@link /documents}
 */
export async function postDocuments(
	data: PostDocumentsMutationRequest,
	config: Partial<RequestConfig<PostDocumentsMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PostDocumentsMutationResponse,
		ResponseErrorConfig<Error>,
		PostDocumentsMutationRequest
	>({
		method: "POST",
		url: getPostDocumentsUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getGetDocumentsUrl() {
	const res = {
		method: "GET",
		url: `http://localhost:8080/documents` as const,
	};
	return res;
}

/**
 * @description List all documents user has access to
 * {@link /documents}
 */
export async function getDocuments(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetDocumentsQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetDocumentsUrl().url.toString(),
		...requestConfig,
	});
	return res;
}

function getGetDocumentsDocumentidUrl(
	documentId: GetDocumentsDocumentidPathParams["documentId"],
) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/documents/${documentId}` as const,
	};
	return res;
}

/**
 * @description Get document by ID
 * {@link /documents/:documentId}
 */
export async function getDocumentsDocumentid(
	documentId: GetDocumentsDocumentidPathParams["documentId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetDocumentsDocumentidQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetDocumentsDocumentidUrl(documentId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getPutDocumentsDocumentidUrl(
	documentId: PutDocumentsDocumentidPathParams["documentId"],
) {
	const res = {
		method: "PUT",
		url: `http://localhost:8080/documents/${documentId}` as const,
	};
	return res;
}

/**
 * @description Update document
 * {@link /documents/:documentId}
 */
export async function putDocumentsDocumentid(
	documentId: PutDocumentsDocumentidPathParams["documentId"],
	data?: PutDocumentsDocumentidMutationRequest,
	config: Partial<RequestConfig<PutDocumentsDocumentidMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PutDocumentsDocumentidMutationResponse,
		ResponseErrorConfig<Error>,
		PutDocumentsDocumentidMutationRequest
	>({
		method: "PUT",
		url: getPutDocumentsDocumentidUrl(documentId).url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getDeleteDocumentsDocumentidUrl(
	documentId: DeleteDocumentsDocumentidPathParams["documentId"],
) {
	const res = {
		method: "DELETE",
		url: `http://localhost:8080/documents/${documentId}` as const,
	};
	return res;
}

/**
 * @description Delete document
 * {@link /documents/:documentId}
 */
export async function deleteDocumentsDocumentid(
	documentId: DeleteDocumentsDocumentidPathParams["documentId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		DeleteDocumentsDocumentidMutationResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "DELETE",
		url: getDeleteDocumentsDocumentidUrl(documentId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getGetDocumentsProjectProjectidUrl(
	projectId: GetDocumentsProjectProjectidPathParams["projectId"],
) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/documents/project/${projectId}` as const,
	};
	return res;
}

/**
 * @description List documents by project ID
 * {@link /documents/project/:projectId}
 */
export async function getDocumentsProjectProjectid(
	projectId: GetDocumentsProjectProjectidPathParams["projectId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetDocumentsProjectProjectidQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetDocumentsProjectProjectidUrl(projectId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getGetColumnsColumnidUrl(
	columnId: GetColumnsColumnidPathParams["columnId"],
) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/columns/${columnId}` as const,
	};
	return res;
}

/**
 * @description Get column by ID
 * {@link /columns/:columnId}
 */
export async function getColumnsColumnid(
	columnId: GetColumnsColumnidPathParams["columnId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetColumnsColumnidQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetColumnsColumnidUrl(columnId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getGetColumnsSprintSprintidUrl(
	sprintId: GetColumnsSprintSprintidPathParams["sprintId"],
) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/columns/sprint/${sprintId}` as const,
	};
	return res;
}

/**
 * @description List fixed columns by sprint ID (Backlog, To Do, Doing, Done)
 * {@link /columns/sprint/:sprintId}
 */
export async function getColumnsSprintSprintid(
	sprintId: GetColumnsSprintSprintidPathParams["sprintId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetColumnsSprintSprintidQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetColumnsSprintSprintidUrl(sprintId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getPostCardsUrl() {
	const res = { method: "POST", url: `http://localhost:8080/cards` as const };
	return res;
}

/**
 * @description Create a new card
 * {@link /cards}
 */
export async function postCards(
	data: PostCardsMutationRequest,
	config: Partial<RequestConfig<PostCardsMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PostCardsMutationResponse,
		ResponseErrorConfig<Error>,
		PostCardsMutationRequest
	>({
		method: "POST",
		url: getPostCardsUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getGetCardsCardidUrl(cardId: GetCardsCardidPathParams["cardId"]) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/cards/${cardId}` as const,
	};
	return res;
}

/**
 * @description Get card by ID with tags
 * {@link /cards/:cardId}
 */
export async function getCardsCardid(
	cardId: GetCardsCardidPathParams["cardId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetCardsCardidQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetCardsCardidUrl(cardId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getPutCardsCardidUrl(cardId: PutCardsCardidPathParams["cardId"]) {
	const res = {
		method: "PUT",
		url: `http://localhost:8080/cards/${cardId}` as const,
	};
	return res;
}

/**
 * @description Update card
 * {@link /cards/:cardId}
 */
export async function putCardsCardid(
	cardId: PutCardsCardidPathParams["cardId"],
	data?: PutCardsCardidMutationRequest,
	config: Partial<RequestConfig<PutCardsCardidMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PutCardsCardidMutationResponse,
		ResponseErrorConfig<Error>,
		PutCardsCardidMutationRequest
	>({
		method: "PUT",
		url: getPutCardsCardidUrl(cardId).url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getDeleteCardsCardidUrl(
	cardId: DeleteCardsCardidPathParams["cardId"],
) {
	const res = {
		method: "DELETE",
		url: `http://localhost:8080/cards/${cardId}` as const,
	};
	return res;
}

/**
 * @description Delete card
 * {@link /cards/:cardId}
 */
export async function deleteCardsCardid(
	cardId: DeleteCardsCardidPathParams["cardId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		DeleteCardsCardidMutationResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "DELETE",
		url: getDeleteCardsCardidUrl(cardId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getGetCardsColumnColumnidUrl(
	columnId: GetCardsColumnColumnidPathParams["columnId"],
) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/cards/column/${columnId}` as const,
	};
	return res;
}

/**
 * @description List cards by column ID
 * {@link /cards/column/:columnId}
 */
export async function getCardsColumnColumnid(
	columnId: GetCardsColumnColumnidPathParams["columnId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetCardsColumnColumnidQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetCardsColumnColumnidUrl(columnId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getGetCardsProjectProjectidUrl(
	projectId: GetCardsProjectProjectidPathParams["projectId"],
) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/cards/project/${projectId}` as const,
	};
	return res;
}

/**
 * @description List cards by project ID
 * {@link /cards/project/:projectId}
 */
export async function getCardsProjectProjectid(
	projectId: GetCardsProjectProjectidPathParams["projectId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetCardsProjectProjectidQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetCardsProjectProjectidUrl(projectId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getGetCardsSprintSprintidUrl(
	sprintId: GetCardsSprintSprintidPathParams["sprintId"],
) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/cards/sprint/${sprintId}` as const,
	};
	return res;
}

/**
 * @description List cards by sprint ID
 * {@link /cards/sprint/:sprintId}
 */
export async function getCardsSprintSprintid(
	sprintId: GetCardsSprintSprintidPathParams["sprintId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetCardsSprintSprintidQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetCardsSprintSprintidUrl(sprintId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getPutCardsCardidMoveUrl(
	cardId: PutCardsCardidMovePathParams["cardId"],
) {
	const res = {
		method: "PUT",
		url: `http://localhost:8080/cards/${cardId}/move` as const,
	};
	return res;
}

/**
 * @description Move card to new position/column
 * {@link /cards/:cardId/move}
 */
export async function putCardsCardidMove(
	cardId: PutCardsCardidMovePathParams["cardId"],
	data: PutCardsCardidMoveMutationRequest,
	config: Partial<RequestConfig<PutCardsCardidMoveMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PutCardsCardidMoveMutationResponse,
		ResponseErrorConfig<Error>,
		PutCardsCardidMoveMutationRequest
	>({
		method: "PUT",
		url: getPutCardsCardidMoveUrl(cardId).url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getPostTagsUrl() {
	const res = { method: "POST", url: `http://localhost:8080/tags` as const };
	return res;
}

/**
 * @description Create a new tag
 * {@link /tags}
 */
export async function postTags(
	data: PostTagsMutationRequest,
	config: Partial<RequestConfig<PostTagsMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PostTagsMutationResponse,
		ResponseErrorConfig<Error>,
		PostTagsMutationRequest
	>({
		method: "POST",
		url: getPostTagsUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getGetTagsTagidUrl(tagId: GetTagsTagidPathParams["tagId"]) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/tags/${tagId}` as const,
	};
	return res;
}

/**
 * @description Get tag by ID
 * {@link /tags/:tagId}
 */
export async function getTagsTagid(
	tagId: GetTagsTagidPathParams["tagId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetTagsTagidQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetTagsTagidUrl(tagId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getPutTagsTagidUrl(tagId: PutTagsTagidPathParams["tagId"]) {
	const res = {
		method: "PUT",
		url: `http://localhost:8080/tags/${tagId}` as const,
	};
	return res;
}

/**
 * @description Update tag
 * {@link /tags/:tagId}
 */
export async function putTagsTagid(
	tagId: PutTagsTagidPathParams["tagId"],
	data?: PutTagsTagidMutationRequest,
	config: Partial<RequestConfig<PutTagsTagidMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PutTagsTagidMutationResponse,
		ResponseErrorConfig<Error>,
		PutTagsTagidMutationRequest
	>({
		method: "PUT",
		url: getPutTagsTagidUrl(tagId).url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getDeleteTagsTagidUrl(tagId: DeleteTagsTagidPathParams["tagId"]) {
	const res = {
		method: "DELETE",
		url: `http://localhost:8080/tags/${tagId}` as const,
	};
	return res;
}

/**
 * @description Delete tag
 * {@link /tags/:tagId}
 */
export async function deleteTagsTagid(
	tagId: DeleteTagsTagidPathParams["tagId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		DeleteTagsTagidMutationResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "DELETE",
		url: getDeleteTagsTagidUrl(tagId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getGetTagsProjectProjectidUrl(
	projectId: GetTagsProjectProjectidPathParams["projectId"],
) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/tags/project/${projectId}` as const,
	};
	return res;
}

/**
 * @description List tags by project ID
 * {@link /tags/project/:projectId}
 */
export async function getTagsProjectProjectid(
	projectId: GetTagsProjectProjectidPathParams["projectId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetTagsProjectProjectidQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetTagsProjectProjectidUrl(projectId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getGetTagsCardCardidUrl(
	cardId: GetTagsCardCardidPathParams["cardId"],
) {
	const res = {
		method: "GET",
		url: `http://localhost:8080/tags/card/${cardId}` as const,
	};
	return res;
}

/**
 * @description List tags by card ID
 * {@link /tags/card/:cardId}
 */
export async function getTagsCardCardid(
	cardId: GetTagsCardCardidPathParams["cardId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		GetTagsCardCardidQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getGetTagsCardCardidUrl(cardId).url.toString(),
		...requestConfig,
	});
	return res;
}

function getPostTagsAssignUrl() {
	const res = {
		method: "POST",
		url: `http://localhost:8080/tags/assign` as const,
	};
	return res;
}

/**
 * @description Assign tag to card
 * {@link /tags/assign}
 */
export async function postTagsAssign(
	data: PostTagsAssignMutationRequest,
	config: Partial<RequestConfig<PostTagsAssignMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PostTagsAssignMutationResponse,
		ResponseErrorConfig<Error>,
		PostTagsAssignMutationRequest
	>({
		method: "POST",
		url: getPostTagsAssignUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res;
}

function getDeleteTagsTagidCardCardidUrl(
	tagId: DeleteTagsTagidCardCardidPathParams["tagId"],
	cardId: DeleteTagsTagidCardCardidPathParams["cardId"],
) {
	const res = {
		method: "DELETE",
		url: `http://localhost:8080/tags/${tagId}/card/${cardId}` as const,
	};
	return res;
}

/**
 * @description Remove tag from card
 * {@link /tags/:tagId/card/:cardId}
 */
export async function deleteTagsTagidCardCardid(
	tagId: DeleteTagsTagidCardCardidPathParams["tagId"],
	cardId: DeleteTagsTagidCardCardidPathParams["cardId"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		DeleteTagsTagidCardCardidMutationResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "DELETE",
		url: getDeleteTagsTagidCardCardidUrl(tagId, cardId).url.toString(),
		...requestConfig,
	});
	return res;
}
