/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Default Response
 */
export type GetHealth200 = any;

export type GetHealthQueryResponse = GetHealth200;

export type GetHealthQuery = {
	Response: GetHealth200;
	Errors: any;
};

/**
 * @description Default Response
 */
export type PostAuthLogin200 = {
	/**
	 * @type object
	 */
	user: {
		/**
		 * @type string, uuid
		 */
		id: string;
		/**
		 * @minLength 1
		 * @maxLength 100
		 * @type string
		 */
		name: string;
		/**
		 * @type string, email
		 */
		email: string;
		/**
		 * @type string, uri
		 */
		avatarUrl?: string | null;
		/**
		 * @type string, date-time
		 */
		createdAt: string;
		/**
		 * @type string, date-time
		 */
		updatedAt: string;
	};
};

export type PostAuthLoginMutationRequest = {
	/**
	 * @type string, email
	 */
	email: string;
	/**
	 * @minLength 4
	 * @type string
	 */
	password: string;
};

export type PostAuthLoginMutationResponse = PostAuthLogin200;

export type PostAuthLoginMutation = {
	Response: PostAuthLogin200;
	Request: PostAuthLoginMutationRequest;
	Errors: any;
};

/**
 * @description Default Response
 */
export type GetAuthGithub200 = {
	/**
	 * @type string, uri
	 */
	url: string;
};

export type GetAuthGithubQueryResponse = GetAuthGithub200;

export type GetAuthGithubQuery = {
	Response: GetAuthGithub200;
	Errors: any;
};

export type GetAuthGithubCallbackQueryParams = {
	/**
	 * @minLength 1
	 * @type string
	 */
	code: string;
	/**
	 * @type string | undefined
	 */
	state?: string;
};

/**
 * @description Default Response
 */
export type GetAuthGithubCallback200 = any;

export type GetAuthGithubCallbackQueryResponse = GetAuthGithubCallback200;

export type GetAuthGithubCallbackQuery = {
	Response: GetAuthGithubCallback200;
	QueryParams: GetAuthGithubCallbackQueryParams;
	Errors: any;
};

/**
 * @description Default Response
 */
export type GetAuthValidate200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
};

export type GetAuthValidateQueryResponse = GetAuthValidate200;

export type GetAuthValidateQuery = {
	Response: GetAuthValidate200;
	Errors: any;
};

export const postAuthLogout204Enum = {} as const;

export type PostAuthLogout204EnumKey =
	(typeof postAuthLogout204Enum)[keyof typeof postAuthLogout204Enum];

/**
 * @description Default Response
 */
export type PostAuthLogout204 = PostAuthLogout204EnumKey | null;

export type PostAuthLogoutMutationResponse = PostAuthLogout204;

export type PostAuthLogoutMutation = {
	Response: PostAuthLogout204;
	Errors: any;
};

export type GetAuthVerifyEmailQueryParams = {
	/**
	 * @minLength 1
	 * @type string
	 */
	token: string;
};

/**
 * @description Default Response
 */
export type GetAuthVerifyEmail200 = {
	/**
	 * @type string
	 */
	message: string;
};

export type GetAuthVerifyEmailQueryResponse = GetAuthVerifyEmail200;

export type GetAuthVerifyEmailQuery = {
	Response: GetAuthVerifyEmail200;
	QueryParams: GetAuthVerifyEmailQueryParams;
	Errors: any;
};

/**
 * @description Default Response
 */
export type PostAuthResendVerification200 = {
	/**
	 * @type string
	 */
	message: string;
};

export type PostAuthResendVerificationMutationRequest = {
	/**
	 * @type string, email
	 */
	email: string;
};

export type PostAuthResendVerificationMutationResponse =
	PostAuthResendVerification200;

export type PostAuthResendVerificationMutation = {
	Response: PostAuthResendVerification200;
	Request: PostAuthResendVerificationMutationRequest;
	Errors: any;
};

/**
 * @description Default Response
 */
export type PostUsers201 = {
	/**
	 * @type string
	 */
	message: string;
};

export type PostUsersMutationRequest = {
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @type string, email
	 */
	email: string;
	/**
	 * @minLength 4
	 * @type string
	 */
	password: string;
};

export type PostUsersMutationResponse = PostUsers201;

export type PostUsersMutation = {
	Response: PostUsers201;
	Request: PostUsersMutationRequest;
	Errors: any;
};

/**
 * @description Default Response
 */
export type GetUsers200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @type string, email
	 */
	email: string;
	/**
	 * @type string, uri
	 */
	avatarUrl?: string | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
}[];

export type GetUsersQueryResponse = GetUsers200;

export type GetUsersQuery = {
	Response: GetUsers200;
	Errors: any;
};

/**
 * @description Default Response
 */
export type PutUsers200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @type string, email
	 */
	email: string;
	/**
	 * @type string, uri
	 */
	avatarUrl?: string | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export type PutUsersMutationRequest = {
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string | undefined
	 */
	name?: string;
	/**
	 * @type string | undefined, email
	 */
	email?: string;
	/**
	 * @type string, uri
	 */
	avatarUrl?: string | null;
};

export type PutUsersMutationResponse = PutUsers200;

export type PutUsersMutation = {
	Response: PutUsers200;
	Request: PutUsersMutationRequest;
	Errors: any;
};

export const deleteUsers204Enum = {} as const;

export type DeleteUsers204EnumKey =
	(typeof deleteUsers204Enum)[keyof typeof deleteUsers204Enum];

/**
 * @description Default Response
 */
export type DeleteUsers204 = DeleteUsers204EnumKey | null;

export type DeleteUsersMutationResponse = DeleteUsers204;

export type DeleteUsersMutation = {
	Response: DeleteUsers204;
	Errors: any;
};

export type GetUsersUseridPathParams = {
	/**
	 * @type string, uuid
	 */
	userId: string;
};

/**
 * @description Default Response
 */
export type GetUsersUserid200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @type string, email
	 */
	email: string;
	/**
	 * @type string, uri
	 */
	avatarUrl?: string | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export type GetUsersUseridQueryResponse = GetUsersUserid200;

export type GetUsersUseridQuery = {
	Response: GetUsersUserid200;
	PathParams: GetUsersUseridPathParams;
	Errors: any;
};

export const postProjects201StatusEnum = {
	active: "active",
	archived: "archived",
	draft: "draft",
} as const;

export type PostProjects201StatusEnumKey =
	(typeof postProjects201StatusEnum)[keyof typeof postProjects201StatusEnum];

export const participantsRoleEnum = {
	owner: "owner",
	admin: "admin",
	contributor: "contributor",
	viewer: "viewer",
} as const;

export type ParticipantsRoleEnumKey =
	(typeof participantsRoleEnum)[keyof typeof participantsRoleEnum];

/**
 * @description Default Response
 */
export type PostProjects201 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	name: string;
	/**
	 * @maxLength 1000
	 * @type string
	 */
	description?: string | null;
	/**
	 * @type string
	 */
	status: PostProjects201StatusEnumKey;
	/**
	 * @type string
	 */
	githubRepositoryId: string | null;
	/**
	 * @type string
	 */
	githubRepositoryFullName: string | null;
	/**
	 * @type array
	 */
	participants: {
		/**
		 * @type string, uuid
		 */
		id: string;
		/**
		 * @minLength 1
		 * @maxLength 100
		 * @type string
		 */
		name: string;
		/**
		 * @type string, email
		 */
		email: string;
		/**
		 * @type string, uri
		 */
		avatarUrl?: string | null;
		/**
		 * @type string
		 */
		role: ParticipantsRoleEnumKey;
	}[];
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export const postProjectsMutationRequestStatusEnum = {
	active: "active",
	archived: "archived",
	draft: "draft",
} as const;

export type PostProjectsMutationRequestStatusEnumKey =
	(typeof postProjectsMutationRequestStatusEnum)[keyof typeof postProjectsMutationRequestStatusEnum];

export type PostProjectsMutationRequest = {
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	name: string;
	/**
	 * @maxLength 1000
	 * @type string | undefined
	 */
	description?: string;
	/**
	 * @default "active"
	 * @type string | undefined
	 */
	status?: PostProjectsMutationRequestStatusEnumKey;
};

export type PostProjectsMutationResponse = PostProjects201;

export type PostProjectsMutation = {
	Response: PostProjects201;
	Request: PostProjectsMutationRequest;
	Errors: any;
};

export const getProjectsQueryParamsStatusEnum = {
	active: "active",
	archived: "archived",
	draft: "draft",
} as const;

export type GetProjectsQueryParamsStatusEnumKey =
	(typeof getProjectsQueryParamsStatusEnum)[keyof typeof getProjectsQueryParamsStatusEnum];

export type GetProjectsQueryParams = {
	/**
	 * @type string | undefined
	 */
	status?: GetProjectsQueryParamsStatusEnumKey;
};

export const getProjects200StatusEnum = {
	active: "active",
	archived: "archived",
	draft: "draft",
} as const;

export type GetProjects200StatusEnumKey =
	(typeof getProjects200StatusEnum)[keyof typeof getProjects200StatusEnum];

export const participantsRoleEnum2 = {
	owner: "owner",
	admin: "admin",
	contributor: "contributor",
	viewer: "viewer",
} as const;

export type ParticipantsRoleEnum2Key =
	(typeof participantsRoleEnum2)[keyof typeof participantsRoleEnum2];

/**
 * @description Default Response
 */
export type GetProjects200 = GetProjects200StatusEnumKey[];

export type GetProjectsQueryResponse = GetProjects200;

export type GetProjectsQuery = {
	Response: GetProjects200;
	QueryParams: GetProjectsQueryParams;
	Errors: any;
};

export type GetProjectsProjectidPathParams = {
	/**
	 * @type string, uuid
	 */
	projectId: string;
};

export const getProjectsProjectid200StatusEnum = {
	active: "active",
	archived: "archived",
	draft: "draft",
} as const;

export type GetProjectsProjectid200StatusEnumKey =
	(typeof getProjectsProjectid200StatusEnum)[keyof typeof getProjectsProjectid200StatusEnum];

export const participantsRoleEnum3 = {
	owner: "owner",
	admin: "admin",
	contributor: "contributor",
	viewer: "viewer",
} as const;

export type ParticipantsRoleEnum3Key =
	(typeof participantsRoleEnum3)[keyof typeof participantsRoleEnum3];

/**
 * @description Default Response
 */
export type GetProjectsProjectid200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	name: string;
	/**
	 * @maxLength 1000
	 * @type string
	 */
	description?: string | null;
	/**
	 * @type string
	 */
	status: GetProjectsProjectid200StatusEnumKey;
	/**
	 * @type string
	 */
	githubRepositoryId: string | null;
	/**
	 * @type string
	 */
	githubRepositoryFullName: string | null;
	/**
	 * @type array
	 */
	participants: {
		/**
		 * @type string, uuid
		 */
		id: string;
		/**
		 * @minLength 1
		 * @maxLength 100
		 * @type string
		 */
		name: string;
		/**
		 * @type string, email
		 */
		email: string;
		/**
		 * @type string, uri
		 */
		avatarUrl?: string | null;
		/**
		 * @type string
		 */
		role: ParticipantsRoleEnum3Key;
	}[];
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export type GetProjectsProjectidQueryResponse = GetProjectsProjectid200;

export type GetProjectsProjectidQuery = {
	Response: GetProjectsProjectid200;
	PathParams: GetProjectsProjectidPathParams;
	Errors: any;
};

export type PutProjectsProjectidPathParams = {
	/**
	 * @type string, uuid
	 */
	projectId: string;
};

export const putProjectsProjectid200StatusEnum = {
	active: "active",
	archived: "archived",
	draft: "draft",
} as const;

export type PutProjectsProjectid200StatusEnumKey =
	(typeof putProjectsProjectid200StatusEnum)[keyof typeof putProjectsProjectid200StatusEnum];

export const participantsRoleEnum4 = {
	owner: "owner",
	admin: "admin",
	contributor: "contributor",
	viewer: "viewer",
} as const;

export type ParticipantsRoleEnum4Key =
	(typeof participantsRoleEnum4)[keyof typeof participantsRoleEnum4];

/**
 * @description Default Response
 */
export type PutProjectsProjectid200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	name: string;
	/**
	 * @maxLength 1000
	 * @type string
	 */
	description?: string | null;
	/**
	 * @type string
	 */
	status: PutProjectsProjectid200StatusEnumKey;
	/**
	 * @type string
	 */
	githubRepositoryId: string | null;
	/**
	 * @type string
	 */
	githubRepositoryFullName: string | null;
	/**
	 * @type array
	 */
	participants: {
		/**
		 * @type string, uuid
		 */
		id: string;
		/**
		 * @minLength 1
		 * @maxLength 100
		 * @type string
		 */
		name: string;
		/**
		 * @type string, email
		 */
		email: string;
		/**
		 * @type string, uri
		 */
		avatarUrl?: string | null;
		/**
		 * @type string
		 */
		role: ParticipantsRoleEnum4Key;
	}[];
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export const putProjectsProjectidMutationRequestStatusEnum = {
	active: "active",
	archived: "archived",
	draft: "draft",
} as const;

export type PutProjectsProjectidMutationRequestStatusEnumKey =
	(typeof putProjectsProjectidMutationRequestStatusEnum)[keyof typeof putProjectsProjectidMutationRequestStatusEnum];

export type PutProjectsProjectidMutationRequest = {
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string | undefined
	 */
	name?: string;
	/**
	 * @maxLength 1000
	 * @type string | undefined
	 */
	description?: string;
	/**
	 * @type string | undefined
	 */
	status?: PutProjectsProjectidMutationRequestStatusEnumKey;
};

export type PutProjectsProjectidMutationResponse = PutProjectsProjectid200;

export type PutProjectsProjectidMutation = {
	Response: PutProjectsProjectid200;
	Request: PutProjectsProjectidMutationRequest;
	PathParams: PutProjectsProjectidPathParams;
	Errors: any;
};

export type DeleteProjectsProjectidPathParams = {
	/**
	 * @type string, uuid
	 */
	projectId: string;
};

export const deleteProjectsProjectid204Enum = {} as const;

export type DeleteProjectsProjectid204EnumKey =
	(typeof deleteProjectsProjectid204Enum)[keyof typeof deleteProjectsProjectid204Enum];

/**
 * @description Default Response
 */
export type DeleteProjectsProjectid204 =
	DeleteProjectsProjectid204EnumKey | null;

export type DeleteProjectsProjectidMutationResponse =
	DeleteProjectsProjectid204;

export type DeleteProjectsProjectidMutation = {
	Response: DeleteProjectsProjectid204;
	PathParams: DeleteProjectsProjectidPathParams;
	Errors: any;
};

export type PostProjectsProjectidRepositoryPathParams = {
	/**
	 * @type string, uuid
	 */
	projectId: string;
};

export const postProjectsProjectidRepository200StatusEnum = {
	active: "active",
	archived: "archived",
	draft: "draft",
} as const;

export type PostProjectsProjectidRepository200StatusEnumKey =
	(typeof postProjectsProjectidRepository200StatusEnum)[keyof typeof postProjectsProjectidRepository200StatusEnum];

export const participantsRoleEnum5 = {
	owner: "owner",
	admin: "admin",
	contributor: "contributor",
	viewer: "viewer",
} as const;

export type ParticipantsRoleEnum5Key =
	(typeof participantsRoleEnum5)[keyof typeof participantsRoleEnum5];

/**
 * @description Default Response
 */
export type PostProjectsProjectidRepository200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	name: string;
	/**
	 * @maxLength 1000
	 * @type string
	 */
	description?: string | null;
	/**
	 * @type string
	 */
	status: PostProjectsProjectidRepository200StatusEnumKey;
	/**
	 * @type string
	 */
	githubRepositoryId: string | null;
	/**
	 * @type string
	 */
	githubRepositoryFullName: string | null;
	/**
	 * @type array
	 */
	participants: {
		/**
		 * @type string, uuid
		 */
		id: string;
		/**
		 * @minLength 1
		 * @maxLength 100
		 * @type string
		 */
		name: string;
		/**
		 * @type string, email
		 */
		email: string;
		/**
		 * @type string, uri
		 */
		avatarUrl?: string | null;
		/**
		 * @type string
		 */
		role: ParticipantsRoleEnum5Key;
	}[];
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export type PostProjectsProjectidRepositoryMutationRequest = {
	/**
	 * @maxLength 9007199254740991
	 * @type integer
	 */
	repositoryId: number;
};

export type PostProjectsProjectidRepositoryMutationResponse =
	PostProjectsProjectidRepository200;

export type PostProjectsProjectidRepositoryMutation = {
	Response: PostProjectsProjectidRepository200;
	Request: PostProjectsProjectidRepositoryMutationRequest;
	PathParams: PostProjectsProjectidRepositoryPathParams;
	Errors: any;
};

export type GetProjectsProjectidParticipantsPathParams = {
	/**
	 * @type string, uuid
	 */
	projectId: string;
};

export const getProjectsProjectidParticipants200RoleEnum = {
	owner: "owner",
	admin: "admin",
	contributor: "contributor",
	viewer: "viewer",
} as const;

export type GetProjectsProjectidParticipants200RoleEnumKey =
	(typeof getProjectsProjectidParticipants200RoleEnum)[keyof typeof getProjectsProjectidParticipants200RoleEnum];

/**
 * @description Default Response
 */
export type GetProjectsProjectidParticipants200 =
	GetProjectsProjectidParticipants200RoleEnumKey[];

export type GetProjectsProjectidParticipantsQueryResponse =
	GetProjectsProjectidParticipants200;

export type GetProjectsProjectidParticipantsQuery = {
	Response: GetProjectsProjectidParticipants200;
	PathParams: GetProjectsProjectidParticipantsPathParams;
	Errors: any;
};

export type PostProjectsProjectidParticipantsPathParams = {
	/**
	 * @type string, uuid
	 */
	projectId: string;
};

export const postProjectsProjectidParticipants201RoleEnum = {
	owner: "owner",
	admin: "admin",
	contributor: "contributor",
	viewer: "viewer",
} as const;

export type PostProjectsProjectidParticipants201RoleEnumKey =
	(typeof postProjectsProjectidParticipants201RoleEnum)[keyof typeof postProjectsProjectidParticipants201RoleEnum];

/**
 * @description Default Response
 */
export type PostProjectsProjectidParticipants201 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @type string, email
	 */
	email: string;
	/**
	 * @type string, uri
	 */
	avatarUrl?: string | null;
	/**
	 * @type string
	 */
	role: PostProjectsProjectidParticipants201RoleEnumKey;
};

export const postProjectsProjectidParticipantsMutationRequestRoleEnum = {
	owner: "owner",
	admin: "admin",
	contributor: "contributor",
	viewer: "viewer",
} as const;

export type PostProjectsProjectidParticipantsMutationRequestRoleEnumKey =
	(typeof postProjectsProjectidParticipantsMutationRequestRoleEnum)[keyof typeof postProjectsProjectidParticipantsMutationRequestRoleEnum];

export type PostProjectsProjectidParticipantsMutationRequest = {
	/**
	 * @type string, uuid
	 */
	userId: string;
	/**
	 * @default "viewer"
	 * @type string | undefined
	 */
	role?: PostProjectsProjectidParticipantsMutationRequestRoleEnumKey;
};

export type PostProjectsProjectidParticipantsMutationResponse =
	PostProjectsProjectidParticipants201;

export type PostProjectsProjectidParticipantsMutation = {
	Response: PostProjectsProjectidParticipants201;
	Request: PostProjectsProjectidParticipantsMutationRequest;
	PathParams: PostProjectsProjectidParticipantsPathParams;
	Errors: any;
};

export type PutProjectsProjectidParticipantsUseridRolePathParams = {
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string, uuid
	 */
	userId: string;
};

export const putProjectsProjectidParticipantsUseridRole200RoleEnum = {
	owner: "owner",
	admin: "admin",
	contributor: "contributor",
	viewer: "viewer",
} as const;

export type PutProjectsProjectidParticipantsUseridRole200RoleEnumKey =
	(typeof putProjectsProjectidParticipantsUseridRole200RoleEnum)[keyof typeof putProjectsProjectidParticipantsUseridRole200RoleEnum];

/**
 * @description Default Response
 */
export type PutProjectsProjectidParticipantsUseridRole200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @type string, email
	 */
	email: string;
	/**
	 * @type string, uri
	 */
	avatarUrl?: string | null;
	/**
	 * @type string
	 */
	role: PutProjectsProjectidParticipantsUseridRole200RoleEnumKey;
};

export const putProjectsProjectidParticipantsUseridRoleMutationRequestRoleEnum =
	{
		owner: "owner",
		admin: "admin",
		contributor: "contributor",
		viewer: "viewer",
	} as const;

export type PutProjectsProjectidParticipantsUseridRoleMutationRequestRoleEnumKey =
	(typeof putProjectsProjectidParticipantsUseridRoleMutationRequestRoleEnum)[keyof typeof putProjectsProjectidParticipantsUseridRoleMutationRequestRoleEnum];

export type PutProjectsProjectidParticipantsUseridRoleMutationRequest = {
	/**
	 * @type string
	 */
	role: PutProjectsProjectidParticipantsUseridRoleMutationRequestRoleEnumKey;
};

export type PutProjectsProjectidParticipantsUseridRoleMutationResponse =
	PutProjectsProjectidParticipantsUseridRole200;

export type PutProjectsProjectidParticipantsUseridRoleMutation = {
	Response: PutProjectsProjectidParticipantsUseridRole200;
	Request: PutProjectsProjectidParticipantsUseridRoleMutationRequest;
	PathParams: PutProjectsProjectidParticipantsUseridRolePathParams;
	Errors: any;
};

export type DeleteProjectsProjectidParticipantsUseridPathParams = {
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string, uuid
	 */
	userId: string;
};

export const deleteProjectsProjectidParticipantsUserid204Enum = {} as const;

export type DeleteProjectsProjectidParticipantsUserid204EnumKey =
	(typeof deleteProjectsProjectidParticipantsUserid204Enum)[keyof typeof deleteProjectsProjectidParticipantsUserid204Enum];

/**
 * @description Default Response
 */
export type DeleteProjectsProjectidParticipantsUserid204 =
	DeleteProjectsProjectidParticipantsUserid204EnumKey | null;

export type DeleteProjectsProjectidParticipantsUseridMutationResponse =
	DeleteProjectsProjectidParticipantsUserid204;

export type DeleteProjectsProjectidParticipantsUseridMutation = {
	Response: DeleteProjectsProjectidParticipantsUserid204;
	PathParams: DeleteProjectsProjectidParticipantsUseridPathParams;
	Errors: any;
};

/**
 * @description Default Response
 */
export type GetGithubRepositories200 = {
	/**
	 * @type number
	 */
	id: number;
	/**
	 * @type string
	 */
	name: string;
	/**
	 * @type string
	 */
	fullName: string;
	/**
	 * @type string
	 */
	description: string | null;
	/**
	 * @type boolean
	 */
	private: boolean;
	/**
	 * @type string, uri
	 */
	url: string;
	/**
	 * @type string, uri
	 */
	cloneUrl: string;
}[];

export type GetGithubRepositoriesQueryResponse = GetGithubRepositories200;

export type GetGithubRepositoriesQuery = {
	Response: GetGithubRepositories200;
	Errors: any;
};

export const postSprints201StatusEnum = {
	active: "active",
	completed: "completed",
	planned: "planned",
} as const;

export type PostSprints201StatusEnumKey =
	(typeof postSprints201StatusEnum)[keyof typeof postSprints201StatusEnum];

/**
 * @description Default Response
 */
export type PostSprints201 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	title: string;
	/**
	 * @maxLength 9007199254740991
	 * @type integer
	 */
	number: number;
	/**
	 * @type string, date-time
	 */
	deadline: string;
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string
	 */
	status: PostSprints201StatusEnumKey | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export const postSprintsMutationRequestStatusEnum = {
	active: "active",
	completed: "completed",
	planned: "planned",
} as const;

export type PostSprintsMutationRequestStatusEnumKey =
	(typeof postSprintsMutationRequestStatusEnum)[keyof typeof postSprintsMutationRequestStatusEnum];

export type PostSprintsMutationRequest = {
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	title: string;
	deadline: any;
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string | undefined
	 */
	status?: PostSprintsMutationRequestStatusEnumKey;
};

export type PostSprintsMutationResponse = PostSprints201;

export type PostSprintsMutation = {
	Response: PostSprints201;
	Request: PostSprintsMutationRequest;
	Errors: any;
};

export type GetSprintsSprintidPathParams = {
	/**
	 * @type string, uuid
	 */
	sprintId: string;
};

export const getSprintsSprintid200StatusEnum = {
	active: "active",
	completed: "completed",
	planned: "planned",
} as const;

export type GetSprintsSprintid200StatusEnumKey =
	(typeof getSprintsSprintid200StatusEnum)[keyof typeof getSprintsSprintid200StatusEnum];

/**
 * @description Default Response
 */
export type GetSprintsSprintid200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	title: string;
	/**
	 * @maxLength 9007199254740991
	 * @type integer
	 */
	number: number;
	/**
	 * @type string, date-time
	 */
	deadline: string;
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string
	 */
	status: GetSprintsSprintid200StatusEnumKey | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export type GetSprintsSprintidQueryResponse = GetSprintsSprintid200;

export type GetSprintsSprintidQuery = {
	Response: GetSprintsSprintid200;
	PathParams: GetSprintsSprintidPathParams;
	Errors: any;
};

export type PutSprintsSprintidPathParams = {
	/**
	 * @type string, uuid
	 */
	sprintId: string;
};

export const putSprintsSprintid200StatusEnum = {
	active: "active",
	completed: "completed",
	planned: "planned",
} as const;

export type PutSprintsSprintid200StatusEnumKey =
	(typeof putSprintsSprintid200StatusEnum)[keyof typeof putSprintsSprintid200StatusEnum];

/**
 * @description Default Response
 */
export type PutSprintsSprintid200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	title: string;
	/**
	 * @maxLength 9007199254740991
	 * @type integer
	 */
	number: number;
	/**
	 * @type string, date-time
	 */
	deadline: string;
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string
	 */
	status: PutSprintsSprintid200StatusEnumKey | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export const putSprintsSprintidMutationRequestStatusEnum = {
	active: "active",
	completed: "completed",
	planned: "planned",
} as const;

export type PutSprintsSprintidMutationRequestStatusEnumKey =
	(typeof putSprintsSprintidMutationRequestStatusEnum)[keyof typeof putSprintsSprintidMutationRequestStatusEnum];

export type PutSprintsSprintidMutationRequest = {
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string | undefined
	 */
	title?: string;
	deadline?: any;
	/**
	 * @type string | undefined
	 */
	status?: PutSprintsSprintidMutationRequestStatusEnumKey;
};

export type PutSprintsSprintidMutationResponse = PutSprintsSprintid200;

export type PutSprintsSprintidMutation = {
	Response: PutSprintsSprintid200;
	Request: PutSprintsSprintidMutationRequest;
	PathParams: PutSprintsSprintidPathParams;
	Errors: any;
};

export type DeleteSprintsSprintidPathParams = {
	/**
	 * @type string, uuid
	 */
	sprintId: string;
};

export const deleteSprintsSprintid204Enum = {} as const;

export type DeleteSprintsSprintid204EnumKey =
	(typeof deleteSprintsSprintid204Enum)[keyof typeof deleteSprintsSprintid204Enum];

/**
 * @description Default Response
 */
export type DeleteSprintsSprintid204 = DeleteSprintsSprintid204EnumKey | null;

export type DeleteSprintsSprintidMutationResponse = DeleteSprintsSprintid204;

export type DeleteSprintsSprintidMutation = {
	Response: DeleteSprintsSprintid204;
	PathParams: DeleteSprintsSprintidPathParams;
	Errors: any;
};

export type GetSprintsProjectProjectidPathParams = {
	/**
	 * @type string, uuid
	 */
	projectId: string;
};

export const getSprintsProjectProjectid200StatusEnum = {
	active: "active",
	completed: "completed",
	planned: "planned",
} as const;

export type GetSprintsProjectProjectid200StatusEnumKey =
	(typeof getSprintsProjectProjectid200StatusEnum)[keyof typeof getSprintsProjectProjectid200StatusEnum];

/**
 * @description Default Response
 */
export type GetSprintsProjectProjectid200 =
	GetSprintsProjectProjectid200StatusEnumKey[];

export type GetSprintsProjectProjectidQueryResponse =
	GetSprintsProjectProjectid200;

export type GetSprintsProjectProjectidQuery = {
	Response: GetSprintsProjectProjectid200;
	PathParams: GetSprintsProjectProjectidPathParams;
	Errors: any;
};

export type GetSprintsProjectProjectidActivePathParams = {
	/**
	 * @type string, uuid
	 */
	projectId: string;
};

export const getSprintsProjectProjectidActive200StatusEnum = {
	active: "active",
	completed: "completed",
	planned: "planned",
} as const;

export type GetSprintsProjectProjectidActive200StatusEnumKey =
	(typeof getSprintsProjectProjectidActive200StatusEnum)[keyof typeof getSprintsProjectProjectidActive200StatusEnum];

/**
 * @description Default Response
 */
export type GetSprintsProjectProjectidActive200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	title: string;
	/**
	 * @maxLength 9007199254740991
	 * @type integer
	 */
	number: number;
	/**
	 * @type string, date-time
	 */
	deadline: string;
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string
	 */
	status: GetSprintsProjectProjectidActive200StatusEnumKey | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
} | null;

export type GetSprintsProjectProjectidActiveQueryResponse =
	GetSprintsProjectProjectidActive200;

export type GetSprintsProjectProjectidActiveQuery = {
	Response: GetSprintsProjectProjectidActive200;
	PathParams: GetSprintsProjectProjectidActivePathParams;
	Errors: any;
};

export type GetSprintsSprintidKanbanPathParams = {
	/**
	 * @type string, uuid
	 */
	sprintId: string;
};

export const cardsComplexityEnum = {
	"1": "1",
	"2": "2",
	"3": "3",
	"5": "5",
	"8": "8",
	"13": "13",
} as const;

export type CardsComplexityEnumKey =
	(typeof cardsComplexityEnum)[keyof typeof cardsComplexityEnum];

export const cardsPriorityEnum = {
	low: "low",
	medium: "medium",
	high: "high",
	critical: "critical",
} as const;

export type CardsPriorityEnumKey =
	(typeof cardsPriorityEnum)[keyof typeof cardsPriorityEnum];

/**
 * @description Default Response
 */
export type GetSprintsSprintidKanban200 = {
	/**
	 * @type string, uuid
	 */
	sprintId: string;
	/**
	 * @type array
	 */
	columns: {
		/**
		 * @type string, uuid
		 */
		id: string;
		/**
		 * @type string
		 */
		name: string;
		/**
		 * @type string
		 */
		sprintId: string;
		/**
		 * @type string, date-time
		 */
		createdAt: string;
		/**
		 * @type string, date-time
		 */
		updatedAt: string;
		/**
		 * @type array
		 */
		cards: {
			/**
			 * @type string, uuid
			 */
			id: string;
			/**
			 * @type string
			 */
			name: string;
			/**
			 * @type string
			 */
			content: string;
			/**
			 * @type string
			 */
			projectId: string;
			/**
			 * @type string
			 */
			sprintId: string;
			/**
			 * @type string
			 */
			columnId: string;
			/**
			 * @type number
			 */
			position: number | null;
			/**
			 * @type string
			 */
			complexity: CardsComplexityEnumKey | null;
			/**
			 * @type string
			 */
			priority: CardsPriorityEnumKey | null;
			/**
			 * @type string
			 */
			githubBranchName: string | null;
			/**
			 * @type string, date-time
			 */
			createdAt: string;
			/**
			 * @type string, date-time
			 */
			updatedAt: string;
			/**
			 * @type array
			 */
			tags: {
				/**
				 * @type string, uuid
				 */
				id: string;
				/**
				 * @type string
				 */
				name: string;
				/**
				 * @type string
				 */
				projectId: string;
				/**
				 * @type string, date-time
				 */
				createdAt: string;
				/**
				 * @type string, date-time
				 */
				updatedAt: string;
			}[];
		}[];
	}[];
};

export type GetSprintsSprintidKanbanQueryResponse = GetSprintsSprintidKanban200;

export type GetSprintsSprintidKanbanQuery = {
	Response: GetSprintsSprintidKanban200;
	PathParams: GetSprintsSprintidKanbanPathParams;
	Errors: any;
};

export type PutSprintsSprintidActivatePathParams = {
	/**
	 * @type string, uuid
	 */
	sprintId: string;
};

export const putSprintsSprintidActivate200StatusEnum = {
	active: "active",
	completed: "completed",
	planned: "planned",
} as const;

export type PutSprintsSprintidActivate200StatusEnumKey =
	(typeof putSprintsSprintidActivate200StatusEnum)[keyof typeof putSprintsSprintidActivate200StatusEnum];

/**
 * @description Default Response
 */
export type PutSprintsSprintidActivate200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	title: string;
	/**
	 * @maxLength 9007199254740991
	 * @type integer
	 */
	number: number;
	/**
	 * @type string, date-time
	 */
	deadline: string;
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string
	 */
	status: PutSprintsSprintidActivate200StatusEnumKey | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export type PutSprintsSprintidActivateMutationResponse =
	PutSprintsSprintidActivate200;

export type PutSprintsSprintidActivateMutation = {
	Response: PutSprintsSprintidActivate200;
	PathParams: PutSprintsSprintidActivatePathParams;
	Errors: any;
};

export type PutSprintsSprintidCompletePathParams = {
	/**
	 * @type string, uuid
	 */
	sprintId: string;
};

export const putSprintsSprintidComplete200StatusEnum = {
	active: "active",
	completed: "completed",
	planned: "planned",
} as const;

export type PutSprintsSprintidComplete200StatusEnumKey =
	(typeof putSprintsSprintidComplete200StatusEnum)[keyof typeof putSprintsSprintidComplete200StatusEnum];

/**
 * @description Default Response
 */
export type PutSprintsSprintidComplete200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	title: string;
	/**
	 * @maxLength 9007199254740991
	 * @type integer
	 */
	number: number;
	/**
	 * @type string, date-time
	 */
	deadline: string;
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string
	 */
	status: PutSprintsSprintidComplete200StatusEnumKey | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export type PutSprintsSprintidCompleteMutationResponse =
	PutSprintsSprintidComplete200;

export type PutSprintsSprintidCompleteMutation = {
	Response: PutSprintsSprintidComplete200;
	PathParams: PutSprintsSprintidCompletePathParams;
	Errors: any;
};

/**
 * @description Default Response
 */
export type PostDocuments201 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	title: string;
	/**
	 * @minLength 1
	 * @type string
	 */
	content: string;
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string, uuid
	 */
	userId: string | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export type PostDocumentsMutationRequest = {
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	title: string;
	/**
	 * @minLength 1
	 * @type string
	 */
	content: string;
	/**
	 * @type string, uuid
	 */
	projectId: string;
};

export type PostDocumentsMutationResponse = PostDocuments201;

export type PostDocumentsMutation = {
	Response: PostDocuments201;
	Request: PostDocumentsMutationRequest;
	Errors: any;
};

/**
 * @description Default Response
 */
export type GetDocuments200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	title: string;
	/**
	 * @minLength 1
	 * @type string
	 */
	content: string;
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string, uuid
	 */
	userId: string | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
}[];

export type GetDocumentsQueryResponse = GetDocuments200;

export type GetDocumentsQuery = {
	Response: GetDocuments200;
	Errors: any;
};

export type GetDocumentsDocumentidPathParams = {
	/**
	 * @type string, uuid
	 */
	documentId: string;
};

/**
 * @description Default Response
 */
export type GetDocumentsDocumentid200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	title: string;
	/**
	 * @minLength 1
	 * @type string
	 */
	content: string;
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string, uuid
	 */
	userId: string | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export type GetDocumentsDocumentidQueryResponse = GetDocumentsDocumentid200;

export type GetDocumentsDocumentidQuery = {
	Response: GetDocumentsDocumentid200;
	PathParams: GetDocumentsDocumentidPathParams;
	Errors: any;
};

export type PutDocumentsDocumentidPathParams = {
	/**
	 * @type string, uuid
	 */
	documentId: string;
};

/**
 * @description Default Response
 */
export type PutDocumentsDocumentid200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	title: string;
	/**
	 * @minLength 1
	 * @type string
	 */
	content: string;
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string, uuid
	 */
	userId: string | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export type PutDocumentsDocumentidMutationRequest = {
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string | undefined
	 */
	title?: string;
	/**
	 * @minLength 1
	 * @type string | undefined
	 */
	content?: string;
};

export type PutDocumentsDocumentidMutationResponse = PutDocumentsDocumentid200;

export type PutDocumentsDocumentidMutation = {
	Response: PutDocumentsDocumentid200;
	Request: PutDocumentsDocumentidMutationRequest;
	PathParams: PutDocumentsDocumentidPathParams;
	Errors: any;
};

export type DeleteDocumentsDocumentidPathParams = {
	/**
	 * @type string, uuid
	 */
	documentId: string;
};

export const deleteDocumentsDocumentid204Enum = {} as const;

export type DeleteDocumentsDocumentid204EnumKey =
	(typeof deleteDocumentsDocumentid204Enum)[keyof typeof deleteDocumentsDocumentid204Enum];

/**
 * @description Default Response
 */
export type DeleteDocumentsDocumentid204 =
	DeleteDocumentsDocumentid204EnumKey | null;

export type DeleteDocumentsDocumentidMutationResponse =
	DeleteDocumentsDocumentid204;

export type DeleteDocumentsDocumentidMutation = {
	Response: DeleteDocumentsDocumentid204;
	PathParams: DeleteDocumentsDocumentidPathParams;
	Errors: any;
};

export type GetDocumentsProjectProjectidPathParams = {
	/**
	 * @type string, uuid
	 */
	projectId: string;
};

/**
 * @description Default Response
 */
export type GetDocumentsProjectProjectid200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 * @type string
	 */
	title: string;
	/**
	 * @minLength 1
	 * @type string
	 */
	content: string;
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string, uuid
	 */
	userId: string | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
}[];

export type GetDocumentsProjectProjectidQueryResponse =
	GetDocumentsProjectProjectid200;

export type GetDocumentsProjectProjectidQuery = {
	Response: GetDocumentsProjectProjectid200;
	PathParams: GetDocumentsProjectProjectidPathParams;
	Errors: any;
};

export type GetColumnsColumnidPathParams = {
	/**
	 * @type string, uuid
	 */
	columnId: string;
};

/**
 * @description Default Response
 */
export type GetColumnsColumnid200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @type string, uuid
	 */
	sprintId: string;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export type GetColumnsColumnidQueryResponse = GetColumnsColumnid200;

export type GetColumnsColumnidQuery = {
	Response: GetColumnsColumnid200;
	PathParams: GetColumnsColumnidPathParams;
	Errors: any;
};

export type GetColumnsSprintSprintidPathParams = {
	/**
	 * @type string, uuid
	 */
	sprintId: string;
};

/**
 * @description Default Response
 */
export type GetColumnsSprintSprintid200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @type string, uuid
	 */
	sprintId: string;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
}[];

export type GetColumnsSprintSprintidQueryResponse = GetColumnsSprintSprintid200;

export type GetColumnsSprintSprintidQuery = {
	Response: GetColumnsSprintSprintid200;
	PathParams: GetColumnsSprintSprintidPathParams;
	Errors: any;
};

export const postCards201ComplexityEnum = {
	"1": "1",
	"2": "2",
	"3": "3",
	"5": "5",
	"8": "8",
	"13": "13",
} as const;

export type PostCards201ComplexityEnumKey =
	(typeof postCards201ComplexityEnum)[keyof typeof postCards201ComplexityEnum];

export const postCards201PriorityEnum = {
	low: "low",
	medium: "medium",
	high: "high",
	critical: "critical",
} as const;

export type PostCards201PriorityEnumKey =
	(typeof postCards201PriorityEnum)[keyof typeof postCards201PriorityEnum];

/**
 * @description Default Response
 */
export type PostCards201 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @maxLength 2000
	 * @default ""
	 * @type string
	 */
	content: string;
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string, uuid
	 */
	sprintId: string;
	/**
	 * @type string, uuid
	 */
	columnId: string;
	/**
	 * @type number
	 */
	position: number | null;
	/**
	 * @type string
	 */
	complexity: PostCards201ComplexityEnumKey | null;
	/**
	 * @type string
	 */
	priority: PostCards201PriorityEnumKey | null;
	/**
	 * @type string
	 */
	githubBranchName: string | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export const postCardsMutationRequestComplexityEnum = {
	"1": "1",
	"2": "2",
	"3": "3",
	"5": "5",
	"8": "8",
	"13": "13",
} as const;

export type PostCardsMutationRequestComplexityEnumKey =
	(typeof postCardsMutationRequestComplexityEnum)[keyof typeof postCardsMutationRequestComplexityEnum];

export const postCardsMutationRequestPriorityEnum = {
	low: "low",
	medium: "medium",
	high: "high",
	critical: "critical",
} as const;

export type PostCardsMutationRequestPriorityEnumKey =
	(typeof postCardsMutationRequestPriorityEnum)[keyof typeof postCardsMutationRequestPriorityEnum];

export type PostCardsMutationRequest = {
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @maxLength 2000
	 * @default ""
	 * @type string | undefined
	 */
	content?: string;
	/**
	 * @type string, uuid
	 */
	columnId: string;
	/**
	 * @type string | undefined
	 */
	complexity?: PostCardsMutationRequestComplexityEnumKey;
	/**
	 * @type string | undefined
	 */
	priority?: PostCardsMutationRequestPriorityEnumKey;
	/**
	 * @default false
	 * @type boolean | undefined
	 */
	createBranch?: boolean;
};

export type PostCardsMutationResponse = PostCards201;

export type PostCardsMutation = {
	Response: PostCards201;
	Request: PostCardsMutationRequest;
	Errors: any;
};

export type GetCardsCardidPathParams = {
	/**
	 * @type string, uuid
	 */
	cardId: string;
};

export const getCardsCardid200ComplexityEnum = {
	"1": "1",
	"2": "2",
	"3": "3",
	"5": "5",
	"8": "8",
	"13": "13",
} as const;

export type GetCardsCardid200ComplexityEnumKey =
	(typeof getCardsCardid200ComplexityEnum)[keyof typeof getCardsCardid200ComplexityEnum];

export const getCardsCardid200PriorityEnum = {
	low: "low",
	medium: "medium",
	high: "high",
	critical: "critical",
} as const;

export type GetCardsCardid200PriorityEnumKey =
	(typeof getCardsCardid200PriorityEnum)[keyof typeof getCardsCardid200PriorityEnum];

/**
 * @description Default Response
 */
export type GetCardsCardid200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @maxLength 2000
	 * @default ""
	 * @type string
	 */
	content: string;
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string, uuid
	 */
	sprintId: string;
	/**
	 * @type string, uuid
	 */
	columnId: string;
	/**
	 * @type number
	 */
	position: number | null;
	/**
	 * @type string
	 */
	complexity: GetCardsCardid200ComplexityEnumKey | null;
	/**
	 * @type string
	 */
	priority: GetCardsCardid200PriorityEnumKey | null;
	/**
	 * @type string
	 */
	githubBranchName: string | null;
	/**
	 * @type array
	 */
	tags: {
		/**
		 * @type string, uuid
		 */
		id: string;
		/**
		 * @minLength 1
		 * @maxLength 100
		 * @type string
		 */
		name: string;
		/**
		 * @type string
		 */
		projectId: string;
		/**
		 * @type string, date-time
		 */
		createdAt: string;
		/**
		 * @type string, date-time
		 */
		updatedAt: string;
	}[];
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export type GetCardsCardidQueryResponse = GetCardsCardid200;

export type GetCardsCardidQuery = {
	Response: GetCardsCardid200;
	PathParams: GetCardsCardidPathParams;
	Errors: any;
};

export type PutCardsCardidPathParams = {
	/**
	 * @type string, uuid
	 */
	cardId: string;
};

export const putCardsCardid200ComplexityEnum = {
	"1": "1",
	"2": "2",
	"3": "3",
	"5": "5",
	"8": "8",
	"13": "13",
} as const;

export type PutCardsCardid200ComplexityEnumKey =
	(typeof putCardsCardid200ComplexityEnum)[keyof typeof putCardsCardid200ComplexityEnum];

export const putCardsCardid200PriorityEnum = {
	low: "low",
	medium: "medium",
	high: "high",
	critical: "critical",
} as const;

export type PutCardsCardid200PriorityEnumKey =
	(typeof putCardsCardid200PriorityEnum)[keyof typeof putCardsCardid200PriorityEnum];

/**
 * @description Default Response
 */
export type PutCardsCardid200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @maxLength 2000
	 * @default ""
	 * @type string
	 */
	content: string;
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string, uuid
	 */
	sprintId: string;
	/**
	 * @type string, uuid
	 */
	columnId: string;
	/**
	 * @type number
	 */
	position: number | null;
	/**
	 * @type string
	 */
	complexity: PutCardsCardid200ComplexityEnumKey | null;
	/**
	 * @type string
	 */
	priority: PutCardsCardid200PriorityEnumKey | null;
	/**
	 * @type string
	 */
	githubBranchName: string | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export const putCardsCardidMutationRequestComplexityEnum = {
	"1": "1",
	"2": "2",
	"3": "3",
	"5": "5",
	"8": "8",
	"13": "13",
} as const;

export type PutCardsCardidMutationRequestComplexityEnumKey =
	(typeof putCardsCardidMutationRequestComplexityEnum)[keyof typeof putCardsCardidMutationRequestComplexityEnum];

export const putCardsCardidMutationRequestPriorityEnum = {
	low: "low",
	medium: "medium",
	high: "high",
	critical: "critical",
} as const;

export type PutCardsCardidMutationRequestPriorityEnumKey =
	(typeof putCardsCardidMutationRequestPriorityEnum)[keyof typeof putCardsCardidMutationRequestPriorityEnum];

export type PutCardsCardidMutationRequest = {
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string | undefined
	 */
	name?: string;
	/**
	 * @maxLength 2000
	 * @default ""
	 * @type string | undefined
	 */
	content?: string;
	/**
	 * @type string | undefined, uuid
	 */
	columnId?: string;
	/**
	 * @type string | undefined
	 */
	complexity?: PutCardsCardidMutationRequestComplexityEnumKey;
	/**
	 * @type string | undefined
	 */
	priority?: PutCardsCardidMutationRequestPriorityEnumKey;
	/**
	 * @type string
	 */
	githubBranchName?: string | null;
};

export type PutCardsCardidMutationResponse = PutCardsCardid200;

export type PutCardsCardidMutation = {
	Response: PutCardsCardid200;
	Request: PutCardsCardidMutationRequest;
	PathParams: PutCardsCardidPathParams;
	Errors: any;
};

export type DeleteCardsCardidPathParams = {
	/**
	 * @type string, uuid
	 */
	cardId: string;
};

export const deleteCardsCardid204Enum = {} as const;

export type DeleteCardsCardid204EnumKey =
	(typeof deleteCardsCardid204Enum)[keyof typeof deleteCardsCardid204Enum];

/**
 * @description Default Response
 */
export type DeleteCardsCardid204 = DeleteCardsCardid204EnumKey | null;

export type DeleteCardsCardidMutationResponse = DeleteCardsCardid204;

export type DeleteCardsCardidMutation = {
	Response: DeleteCardsCardid204;
	PathParams: DeleteCardsCardidPathParams;
	Errors: any;
};

export type GetCardsColumnColumnidPathParams = {
	/**
	 * @type string, uuid
	 */
	columnId: string;
};

export const getCardsColumnColumnid200ComplexityEnum = {
	"1": "1",
	"2": "2",
	"3": "3",
	"5": "5",
	"8": "8",
	"13": "13",
} as const;

export type GetCardsColumnColumnid200ComplexityEnumKey =
	(typeof getCardsColumnColumnid200ComplexityEnum)[keyof typeof getCardsColumnColumnid200ComplexityEnum];

export const getCardsColumnColumnid200PriorityEnum = {
	low: "low",
	medium: "medium",
	high: "high",
	critical: "critical",
} as const;

export type GetCardsColumnColumnid200PriorityEnumKey =
	(typeof getCardsColumnColumnid200PriorityEnum)[keyof typeof getCardsColumnColumnid200PriorityEnum];

/**
 * @description Default Response
 */
export type GetCardsColumnColumnid200 =
	GetCardsColumnColumnid200ComplexityEnumKey[];

export type GetCardsColumnColumnidQueryResponse = GetCardsColumnColumnid200;

export type GetCardsColumnColumnidQuery = {
	Response: GetCardsColumnColumnid200;
	PathParams: GetCardsColumnColumnidPathParams;
	Errors: any;
};

export type GetCardsProjectProjectidPathParams = {
	/**
	 * @type string, uuid
	 */
	projectId: string;
};

export const getCardsProjectProjectid200ComplexityEnum = {
	"1": "1",
	"2": "2",
	"3": "3",
	"5": "5",
	"8": "8",
	"13": "13",
} as const;

export type GetCardsProjectProjectid200ComplexityEnumKey =
	(typeof getCardsProjectProjectid200ComplexityEnum)[keyof typeof getCardsProjectProjectid200ComplexityEnum];

export const getCardsProjectProjectid200PriorityEnum = {
	low: "low",
	medium: "medium",
	high: "high",
	critical: "critical",
} as const;

export type GetCardsProjectProjectid200PriorityEnumKey =
	(typeof getCardsProjectProjectid200PriorityEnum)[keyof typeof getCardsProjectProjectid200PriorityEnum];

/**
 * @description Default Response
 */
export type GetCardsProjectProjectid200 =
	GetCardsProjectProjectid200ComplexityEnumKey[];

export type GetCardsProjectProjectidQueryResponse = GetCardsProjectProjectid200;

export type GetCardsProjectProjectidQuery = {
	Response: GetCardsProjectProjectid200;
	PathParams: GetCardsProjectProjectidPathParams;
	Errors: any;
};

export type GetCardsSprintSprintidPathParams = {
	/**
	 * @type string, uuid
	 */
	sprintId: string;
};

export const getCardsSprintSprintid200ComplexityEnum = {
	"1": "1",
	"2": "2",
	"3": "3",
	"5": "5",
	"8": "8",
	"13": "13",
} as const;

export type GetCardsSprintSprintid200ComplexityEnumKey =
	(typeof getCardsSprintSprintid200ComplexityEnum)[keyof typeof getCardsSprintSprintid200ComplexityEnum];

export const getCardsSprintSprintid200PriorityEnum = {
	low: "low",
	medium: "medium",
	high: "high",
	critical: "critical",
} as const;

export type GetCardsSprintSprintid200PriorityEnumKey =
	(typeof getCardsSprintSprintid200PriorityEnum)[keyof typeof getCardsSprintSprintid200PriorityEnum];

/**
 * @description Default Response
 */
export type GetCardsSprintSprintid200 =
	GetCardsSprintSprintid200ComplexityEnumKey[];

export type GetCardsSprintSprintidQueryResponse = GetCardsSprintSprintid200;

export type GetCardsSprintSprintidQuery = {
	Response: GetCardsSprintSprintid200;
	PathParams: GetCardsSprintSprintidPathParams;
	Errors: any;
};

export type PutCardsCardidMovePathParams = {
	/**
	 * @type string, uuid
	 */
	cardId: string;
};

export const putCardsCardidMove200ComplexityEnum = {
	"1": "1",
	"2": "2",
	"3": "3",
	"5": "5",
	"8": "8",
	"13": "13",
} as const;

export type PutCardsCardidMove200ComplexityEnumKey =
	(typeof putCardsCardidMove200ComplexityEnum)[keyof typeof putCardsCardidMove200ComplexityEnum];

export const putCardsCardidMove200PriorityEnum = {
	low: "low",
	medium: "medium",
	high: "high",
	critical: "critical",
} as const;

export type PutCardsCardidMove200PriorityEnumKey =
	(typeof putCardsCardidMove200PriorityEnum)[keyof typeof putCardsCardidMove200PriorityEnum];

/**
 * @description Default Response
 */
export type PutCardsCardidMove200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @maxLength 2000
	 * @default ""
	 * @type string
	 */
	content: string;
	/**
	 * @type string, uuid
	 */
	projectId: string;
	/**
	 * @type string, uuid
	 */
	sprintId: string;
	/**
	 * @type string, uuid
	 */
	columnId: string;
	/**
	 * @type number
	 */
	position: number | null;
	/**
	 * @type string
	 */
	complexity: PutCardsCardidMove200ComplexityEnumKey | null;
	/**
	 * @type string
	 */
	priority: PutCardsCardidMove200PriorityEnumKey | null;
	/**
	 * @type string
	 */
	githubBranchName: string | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export type PutCardsCardidMoveMutationRequest = {
	/**
	 * @type string, uuid
	 */
	targetColumnId: string;
	/**
	 * @minLength 0
	 * @type number
	 */
	newPosition: number;
};

export type PutCardsCardidMoveMutationResponse = PutCardsCardidMove200;

export type PutCardsCardidMoveMutation = {
	Response: PutCardsCardidMove200;
	Request: PutCardsCardidMoveMutationRequest;
	PathParams: PutCardsCardidMovePathParams;
	Errors: any;
};

/**
 * @description Default Response
 */
export type PostTags201 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @type string, uuid
	 */
	projectId: string | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export type PostTagsMutationRequest = {
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @type string, uuid
	 */
	projectId: string;
};

export type PostTagsMutationResponse = PostTags201;

export type PostTagsMutation = {
	Response: PostTags201;
	Request: PostTagsMutationRequest;
	Errors: any;
};

export type GetTagsTagidPathParams = {
	/**
	 * @type string, uuid
	 */
	tagId: string;
};

/**
 * @description Default Response
 */
export type GetTagsTagid200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @type string, uuid
	 */
	projectId: string | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export type GetTagsTagidQueryResponse = GetTagsTagid200;

export type GetTagsTagidQuery = {
	Response: GetTagsTagid200;
	PathParams: GetTagsTagidPathParams;
	Errors: any;
};

export type PutTagsTagidPathParams = {
	/**
	 * @type string, uuid
	 */
	tagId: string;
};

/**
 * @description Default Response
 */
export type PutTagsTagid200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @type string, uuid
	 */
	projectId: string | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};

export type PutTagsTagidMutationRequest = {
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string | undefined
	 */
	name?: string;
};

export type PutTagsTagidMutationResponse = PutTagsTagid200;

export type PutTagsTagidMutation = {
	Response: PutTagsTagid200;
	Request: PutTagsTagidMutationRequest;
	PathParams: PutTagsTagidPathParams;
	Errors: any;
};

export type DeleteTagsTagidPathParams = {
	/**
	 * @type string, uuid
	 */
	tagId: string;
};

export const deleteTagsTagid204Enum = {} as const;

export type DeleteTagsTagid204EnumKey =
	(typeof deleteTagsTagid204Enum)[keyof typeof deleteTagsTagid204Enum];

/**
 * @description Default Response
 */
export type DeleteTagsTagid204 = DeleteTagsTagid204EnumKey | null;

export type DeleteTagsTagidMutationResponse = DeleteTagsTagid204;

export type DeleteTagsTagidMutation = {
	Response: DeleteTagsTagid204;
	PathParams: DeleteTagsTagidPathParams;
	Errors: any;
};

export type GetTagsProjectProjectidPathParams = {
	/**
	 * @type string, uuid
	 */
	projectId: string;
};

/**
 * @description Default Response
 */
export type GetTagsProjectProjectid200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @type string, uuid
	 */
	projectId: string | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
}[];

export type GetTagsProjectProjectidQueryResponse = GetTagsProjectProjectid200;

export type GetTagsProjectProjectidQuery = {
	Response: GetTagsProjectProjectid200;
	PathParams: GetTagsProjectProjectidPathParams;
	Errors: any;
};

export type GetTagsCardCardidPathParams = {
	/**
	 * @type string, uuid
	 */
	cardId: string;
};

/**
 * @description Default Response
 */
export type GetTagsCardCardid200 = {
	/**
	 * @type string, uuid
	 */
	id: string;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @type string
	 */
	name: string;
	/**
	 * @type string, uuid
	 */
	projectId: string | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
}[];

export type GetTagsCardCardidQueryResponse = GetTagsCardCardid200;

export type GetTagsCardCardidQuery = {
	Response: GetTagsCardCardid200;
	PathParams: GetTagsCardCardidPathParams;
	Errors: any;
};

export const postTagsAssign204Enum = {} as const;

export type PostTagsAssign204EnumKey =
	(typeof postTagsAssign204Enum)[keyof typeof postTagsAssign204Enum];

/**
 * @description Default Response
 */
export type PostTagsAssign204 = PostTagsAssign204EnumKey | null;

export type PostTagsAssignMutationRequest = {
	/**
	 * @type string, uuid
	 */
	tagId: string;
	/**
	 * @type string, uuid
	 */
	cardId: string;
};

export type PostTagsAssignMutationResponse = PostTagsAssign204;

export type PostTagsAssignMutation = {
	Response: PostTagsAssign204;
	Request: PostTagsAssignMutationRequest;
	Errors: any;
};

export type DeleteTagsTagidCardCardidPathParams = {
	/**
	 * @type string, uuid
	 */
	tagId: string;
	/**
	 * @type string, uuid
	 */
	cardId: string;
};

export const deleteTagsTagidCardCardid204Enum = {} as const;

export type DeleteTagsTagidCardCardid204EnumKey =
	(typeof deleteTagsTagidCardCardid204Enum)[keyof typeof deleteTagsTagidCardCardid204Enum];

/**
 * @description Default Response
 */
export type DeleteTagsTagidCardCardid204 =
	DeleteTagsTagidCardCardid204EnumKey | null;

export type DeleteTagsTagidCardCardidMutationResponse =
	DeleteTagsTagidCardCardid204;

export type DeleteTagsTagidCardCardidMutation = {
	Response: DeleteTagsTagidCardCardid204;
	PathParams: DeleteTagsTagidCardCardidPathParams;
	Errors: any;
};
