// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8080' | (string & {});
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostAuthLoginData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginResponses = {
    /**
     * Default Response
     */
    200: {
        user: {
            id: string;
            name: string;
            email: string;
            avatarUrl?: string | null;
            createdAt: string;
            updatedAt: string;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetAuthGithubData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/github';
};

export type GetAuthGithubResponses = {
    /**
     * Default Response
     */
    200: {
        url: string;
    };
};

export type GetAuthGithubResponse = GetAuthGithubResponses[keyof GetAuthGithubResponses];

export type GetAuthGithubCallbackData = {
    body?: never;
    path?: never;
    query: {
        code: string;
        state?: string;
    };
    url: '/auth/github/callback';
};

export type GetAuthGithubCallbackResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetAuthValidateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/validate';
};

export type GetAuthValidateResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
    };
};

export type GetAuthValidateResponse = GetAuthValidateResponses[keyof GetAuthValidateResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * Default Response
     */
    204: null;
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type GetAuthVerifyEmailData = {
    body?: never;
    path?: never;
    query: {
        token: string;
    };
    url: '/auth/verify-email';
};

export type GetAuthVerifyEmailResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type GetAuthVerifyEmailResponse = GetAuthVerifyEmailResponses[keyof GetAuthVerifyEmailResponses];

export type PostAuthResendVerificationData = {
    body: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/auth/resend-verification';
};

export type PostAuthResendVerificationResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type PostAuthResendVerificationResponse = PostAuthResendVerificationResponses[keyof PostAuthResendVerificationResponses];

export type DeleteUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type DeleteUsersResponses = {
    /**
     * Default Response
     */
    204: null;
};

export type DeleteUsersResponse = DeleteUsersResponses[keyof DeleteUsersResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type GetUsersResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        email: string;
        avatarUrl?: string | null;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostUsersData = {
    body: {
        name: string;
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/users';
};

export type PostUsersResponses = {
    /**
     * Default Response
     */
    201: {
        message: string;
    };
};

export type PostUsersResponse = PostUsersResponses[keyof PostUsersResponses];

export type PutUsersData = {
    body?: {
        name?: string;
        email?: string;
        avatarUrl?: string | null;
    };
    path?: never;
    query?: never;
    url: '/users';
};

export type PutUsersResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        email: string;
        avatarUrl?: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type PutUsersResponse = PutUsersResponses[keyof PutUsersResponses];

export type GetUsersByUserIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}';
};

export type GetUsersByUserIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        email: string;
        avatarUrl?: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetUsersByUserIdResponse = GetUsersByUserIdResponses[keyof GetUsersByUserIdResponses];

export type GetProjectsData = {
    body?: never;
    path?: never;
    query?: {
        status?: 'active' | 'archived' | 'draft';
    };
    url: '/projects';
};

export type GetProjectsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        description?: string | null;
        status: 'active' | 'archived' | 'draft';
        githubRepositoryId: string | null;
        githubRepositoryFullName: string | null;
        participants: Array<{
            id: string;
            name: string;
            email: string;
            avatarUrl?: string | null;
            role: 'owner' | 'admin' | 'contributor' | 'viewer';
        }>;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetProjectsResponse = GetProjectsResponses[keyof GetProjectsResponses];

export type PostProjectsData = {
    body: {
        name: string;
        description?: string;
        status?: 'active' | 'archived' | 'draft';
    };
    path?: never;
    query?: never;
    url: '/projects';
};

export type PostProjectsResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        name: string;
        description?: string | null;
        status: 'active' | 'archived' | 'draft';
        githubRepositoryId: string | null;
        githubRepositoryFullName: string | null;
        participants: Array<{
            id: string;
            name: string;
            email: string;
            avatarUrl?: string | null;
            role: 'owner' | 'admin' | 'contributor' | 'viewer';
        }>;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostProjectsResponse = PostProjectsResponses[keyof PostProjectsResponses];

export type DeleteProjectsByProjectIdData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/projects/{projectId}';
};

export type DeleteProjectsByProjectIdResponses = {
    /**
     * Default Response
     */
    204: null;
};

export type DeleteProjectsByProjectIdResponse = DeleteProjectsByProjectIdResponses[keyof DeleteProjectsByProjectIdResponses];

export type GetProjectsByProjectIdData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/projects/{projectId}';
};

export type GetProjectsByProjectIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        description?: string | null;
        status: 'active' | 'archived' | 'draft';
        githubRepositoryId: string | null;
        githubRepositoryFullName: string | null;
        participants: Array<{
            id: string;
            name: string;
            email: string;
            avatarUrl?: string | null;
            role: 'owner' | 'admin' | 'contributor' | 'viewer';
        }>;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetProjectsByProjectIdResponse = GetProjectsByProjectIdResponses[keyof GetProjectsByProjectIdResponses];

export type PutProjectsByProjectIdData = {
    body?: {
        name?: string;
        description?: string;
        status?: 'active' | 'archived' | 'draft';
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/projects/{projectId}';
};

export type PutProjectsByProjectIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        description?: string | null;
        status: 'active' | 'archived' | 'draft';
        githubRepositoryId: string | null;
        githubRepositoryFullName: string | null;
        participants: Array<{
            id: string;
            name: string;
            email: string;
            avatarUrl?: string | null;
            role: 'owner' | 'admin' | 'contributor' | 'viewer';
        }>;
        createdAt: string;
        updatedAt: string;
    };
};

export type PutProjectsByProjectIdResponse = PutProjectsByProjectIdResponses[keyof PutProjectsByProjectIdResponses];

export type PostProjectsByProjectIdRepositoryData = {
    body: {
        repositoryId: number;
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/projects/{projectId}/repository';
};

export type PostProjectsByProjectIdRepositoryResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        description?: string | null;
        status: 'active' | 'archived' | 'draft';
        githubRepositoryId: string | null;
        githubRepositoryFullName: string | null;
        participants: Array<{
            id: string;
            name: string;
            email: string;
            avatarUrl?: string | null;
            role: 'owner' | 'admin' | 'contributor' | 'viewer';
        }>;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostProjectsByProjectIdRepositoryResponse = PostProjectsByProjectIdRepositoryResponses[keyof PostProjectsByProjectIdRepositoryResponses];

export type GetProjectsByProjectIdParticipantsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/projects/{projectId}/participants';
};

export type GetProjectsByProjectIdParticipantsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        email: string;
        avatarUrl?: string | null;
        role: 'owner' | 'admin' | 'contributor' | 'viewer';
    }>;
};

export type GetProjectsByProjectIdParticipantsResponse = GetProjectsByProjectIdParticipantsResponses[keyof GetProjectsByProjectIdParticipantsResponses];

export type PostProjectsByProjectIdParticipantsData = {
    body: {
        userId: string;
        role?: 'owner' | 'admin' | 'contributor' | 'viewer';
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/projects/{projectId}/participants';
};

export type PostProjectsByProjectIdParticipantsResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        name: string;
        email: string;
        avatarUrl?: string | null;
        role: 'owner' | 'admin' | 'contributor' | 'viewer';
    };
};

export type PostProjectsByProjectIdParticipantsResponse = PostProjectsByProjectIdParticipantsResponses[keyof PostProjectsByProjectIdParticipantsResponses];

export type PutProjectsByProjectIdParticipantsByUserIdRoleData = {
    body: {
        role: 'owner' | 'admin' | 'contributor' | 'viewer';
    };
    path: {
        projectId: string;
        userId: string;
    };
    query?: never;
    url: '/projects/{projectId}/participants/{userId}/role';
};

export type PutProjectsByProjectIdParticipantsByUserIdRoleResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        email: string;
        avatarUrl?: string | null;
        role: 'owner' | 'admin' | 'contributor' | 'viewer';
    };
};

export type PutProjectsByProjectIdParticipantsByUserIdRoleResponse = PutProjectsByProjectIdParticipantsByUserIdRoleResponses[keyof PutProjectsByProjectIdParticipantsByUserIdRoleResponses];

export type DeleteProjectsByProjectIdParticipantsByUserIdData = {
    body?: never;
    path: {
        projectId: string;
        userId: string;
    };
    query?: never;
    url: '/projects/{projectId}/participants/{userId}';
};

export type DeleteProjectsByProjectIdParticipantsByUserIdResponses = {
    /**
     * Default Response
     */
    204: null;
};

export type DeleteProjectsByProjectIdParticipantsByUserIdResponse = DeleteProjectsByProjectIdParticipantsByUserIdResponses[keyof DeleteProjectsByProjectIdParticipantsByUserIdResponses];

export type GetGithubRepositoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/github/repositories';
};

export type GetGithubRepositoriesResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: number;
        name: string;
        fullName: string;
        description: string | null;
        private: boolean;
        url: string;
        cloneUrl: string;
    }>;
};

export type GetGithubRepositoriesResponse = GetGithubRepositoriesResponses[keyof GetGithubRepositoriesResponses];

export type PostSprintsData = {
    body: {
        title: string;
        deadline: unknown;
        projectId: string;
        status?: 'active' | 'completed' | 'planned';
    };
    path?: never;
    query?: never;
    url: '/sprints';
};

export type PostSprintsResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        title: string;
        number: number;
        deadline: string;
        projectId: string;
        status: 'active' | 'completed' | 'planned';
        createdAt: string;
        updatedAt: string;
    };
};

export type PostSprintsResponse = PostSprintsResponses[keyof PostSprintsResponses];

export type DeleteSprintsBySprintIdData = {
    body?: never;
    path: {
        sprintId: string;
    };
    query?: never;
    url: '/sprints/{sprintId}';
};

export type DeleteSprintsBySprintIdResponses = {
    /**
     * Default Response
     */
    204: null;
};

export type DeleteSprintsBySprintIdResponse = DeleteSprintsBySprintIdResponses[keyof DeleteSprintsBySprintIdResponses];

export type GetSprintsBySprintIdData = {
    body?: never;
    path: {
        sprintId: string;
    };
    query?: never;
    url: '/sprints/{sprintId}';
};

export type GetSprintsBySprintIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        title: string;
        number: number;
        deadline: string;
        projectId: string;
        status: 'active' | 'completed' | 'planned';
        createdAt: string;
        updatedAt: string;
    };
};

export type GetSprintsBySprintIdResponse = GetSprintsBySprintIdResponses[keyof GetSprintsBySprintIdResponses];

export type PutSprintsBySprintIdData = {
    body?: {
        title?: string;
        deadline?: unknown;
        status?: 'active' | 'completed' | 'planned';
    };
    path: {
        sprintId: string;
    };
    query?: never;
    url: '/sprints/{sprintId}';
};

export type PutSprintsBySprintIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        title: string;
        number: number;
        deadline: string;
        projectId: string;
        status: 'active' | 'completed' | 'planned';
        createdAt: string;
        updatedAt: string;
    };
};

export type PutSprintsBySprintIdResponse = PutSprintsBySprintIdResponses[keyof PutSprintsBySprintIdResponses];

export type GetSprintsProjectByProjectIdData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/sprints/project/{projectId}';
};

export type GetSprintsProjectByProjectIdResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        title: string;
        number: number;
        deadline: string;
        projectId: string;
        status: 'active' | 'completed' | 'planned';
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetSprintsProjectByProjectIdResponse = GetSprintsProjectByProjectIdResponses[keyof GetSprintsProjectByProjectIdResponses];

export type GetSprintsProjectByProjectIdActiveData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/sprints/project/{projectId}/active';
};

export type GetSprintsProjectByProjectIdActiveResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        title: string;
        number: number;
        deadline: string;
        projectId: string;
        status: 'active' | 'completed' | 'planned';
        createdAt: string;
        updatedAt: string;
    } | null;
};

export type GetSprintsProjectByProjectIdActiveResponse = GetSprintsProjectByProjectIdActiveResponses[keyof GetSprintsProjectByProjectIdActiveResponses];

export type GetSprintsBySprintIdKanbanData = {
    body?: never;
    path: {
        sprintId: string;
    };
    query?: never;
    url: '/sprints/{sprintId}/kanban';
};

export type GetSprintsBySprintIdKanbanResponses = {
    /**
     * Default Response
     */
    200: {
        sprintId: string;
        columns: Array<{
            id: string;
            name: string;
            sprintId: string;
            createdAt: string;
            updatedAt: string;
            cards: Array<{
                id: string;
                name: string;
                content: string;
                projectId: string;
                sprintId: string;
                columnId: string;
                position: number | null;
                complexity: '1' | '2' | '3' | '5' | '8' | '13';
                priority: 'low' | 'medium' | 'high' | 'critical';
                githubBranchName: string | null;
                createdAt: string;
                updatedAt: string;
                tags: Array<{
                    id: string;
                    name: string;
                    projectId: string;
                    createdAt: string;
                    updatedAt: string;
                }>;
            }>;
        }>;
    };
};

export type GetSprintsBySprintIdKanbanResponse = GetSprintsBySprintIdKanbanResponses[keyof GetSprintsBySprintIdKanbanResponses];

export type PutSprintsBySprintIdActivateData = {
    body?: never;
    path: {
        sprintId: string;
    };
    query?: never;
    url: '/sprints/{sprintId}/activate';
};

export type PutSprintsBySprintIdActivateResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        title: string;
        number: number;
        deadline: string;
        projectId: string;
        status: 'active' | 'completed' | 'planned';
        createdAt: string;
        updatedAt: string;
    };
};

export type PutSprintsBySprintIdActivateResponse = PutSprintsBySprintIdActivateResponses[keyof PutSprintsBySprintIdActivateResponses];

export type PutSprintsBySprintIdCompleteData = {
    body?: never;
    path: {
        sprintId: string;
    };
    query?: never;
    url: '/sprints/{sprintId}/complete';
};

export type PutSprintsBySprintIdCompleteResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        title: string;
        number: number;
        deadline: string;
        projectId: string;
        status: 'active' | 'completed' | 'planned';
        createdAt: string;
        updatedAt: string;
    };
};

export type PutSprintsBySprintIdCompleteResponse = PutSprintsBySprintIdCompleteResponses[keyof PutSprintsBySprintIdCompleteResponses];

export type GetDocumentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/documents';
};

export type GetDocumentsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        title: string;
        content: string;
        projectId: string;
        userId: string | null;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetDocumentsResponse = GetDocumentsResponses[keyof GetDocumentsResponses];

export type PostDocumentsData = {
    body: {
        title: string;
        content: string;
        projectId: string;
    };
    path?: never;
    query?: never;
    url: '/documents';
};

export type PostDocumentsResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        title: string;
        content: string;
        projectId: string;
        userId: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostDocumentsResponse = PostDocumentsResponses[keyof PostDocumentsResponses];

export type DeleteDocumentsByDocumentIdData = {
    body?: never;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}';
};

export type DeleteDocumentsByDocumentIdResponses = {
    /**
     * Default Response
     */
    204: null;
};

export type DeleteDocumentsByDocumentIdResponse = DeleteDocumentsByDocumentIdResponses[keyof DeleteDocumentsByDocumentIdResponses];

export type GetDocumentsByDocumentIdData = {
    body?: never;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}';
};

export type GetDocumentsByDocumentIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        title: string;
        content: string;
        projectId: string;
        userId: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetDocumentsByDocumentIdResponse = GetDocumentsByDocumentIdResponses[keyof GetDocumentsByDocumentIdResponses];

export type PutDocumentsByDocumentIdData = {
    body?: {
        title?: string;
        content?: string;
    };
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}';
};

export type PutDocumentsByDocumentIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        title: string;
        content: string;
        projectId: string;
        userId: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type PutDocumentsByDocumentIdResponse = PutDocumentsByDocumentIdResponses[keyof PutDocumentsByDocumentIdResponses];

export type GetDocumentsProjectByProjectIdData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/documents/project/{projectId}';
};

export type GetDocumentsProjectByProjectIdResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        title: string;
        content: string;
        projectId: string;
        userId: string | null;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetDocumentsProjectByProjectIdResponse = GetDocumentsProjectByProjectIdResponses[keyof GetDocumentsProjectByProjectIdResponses];

export type GetColumnsByColumnIdData = {
    body?: never;
    path: {
        columnId: string;
    };
    query?: never;
    url: '/columns/{columnId}';
};

export type GetColumnsByColumnIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        sprintId: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetColumnsByColumnIdResponse = GetColumnsByColumnIdResponses[keyof GetColumnsByColumnIdResponses];

export type GetColumnsSprintBySprintIdData = {
    body?: never;
    path: {
        sprintId: string;
    };
    query?: never;
    url: '/columns/sprint/{sprintId}';
};

export type GetColumnsSprintBySprintIdResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        sprintId: string;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetColumnsSprintBySprintIdResponse = GetColumnsSprintBySprintIdResponses[keyof GetColumnsSprintBySprintIdResponses];

export type PostCardsData = {
    body: {
        name: string;
        content?: string;
        columnId: string;
        complexity: '1' | '2' | '3' | '5' | '8' | '13';
        priority: 'low' | 'medium' | 'high' | 'critical';
        createBranch?: boolean;
    };
    path?: never;
    query?: never;
    url: '/cards';
};

export type PostCardsResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        name: string;
        content: string;
        projectId: string;
        sprintId: string;
        columnId: string;
        position: number;
        complexity: '1' | '2' | '3' | '5' | '8' | '13';
        priority: 'low' | 'medium' | 'high' | 'critical';
        githubBranchName: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostCardsResponse = PostCardsResponses[keyof PostCardsResponses];

export type DeleteCardsByCardIdData = {
    body?: never;
    path: {
        cardId: string;
    };
    query?: never;
    url: '/cards/{cardId}';
};

export type DeleteCardsByCardIdResponses = {
    /**
     * Default Response
     */
    204: null;
};

export type DeleteCardsByCardIdResponse = DeleteCardsByCardIdResponses[keyof DeleteCardsByCardIdResponses];

export type GetCardsByCardIdData = {
    body?: never;
    path: {
        cardId: string;
    };
    query?: never;
    url: '/cards/{cardId}';
};

export type GetCardsByCardIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        content: string;
        projectId: string;
        sprintId: string;
        columnId: string;
        position: number;
        complexity: '1' | '2' | '3' | '5' | '8' | '13';
        priority: 'low' | 'medium' | 'high' | 'critical';
        githubBranchName: string | null;
        tags: Array<{
            id: string;
            name: string;
            projectId: string;
            createdAt: string;
            updatedAt: string;
        }>;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetCardsByCardIdResponse = GetCardsByCardIdResponses[keyof GetCardsByCardIdResponses];

export type PutCardsByCardIdData = {
    body?: {
        name?: string;
        content?: string;
        columnId?: string;
        complexity?: '1' | '2' | '3' | '5' | '8' | '13';
        priority?: 'low' | 'medium' | 'high' | 'critical';
        githubBranchName?: string | null;
    };
    path: {
        cardId: string;
    };
    query?: never;
    url: '/cards/{cardId}';
};

export type PutCardsByCardIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        content: string;
        projectId: string;
        sprintId: string;
        columnId: string;
        position: number;
        complexity: '1' | '2' | '3' | '5' | '8' | '13';
        priority: 'low' | 'medium' | 'high' | 'critical';
        githubBranchName: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type PutCardsByCardIdResponse = PutCardsByCardIdResponses[keyof PutCardsByCardIdResponses];

export type GetCardsColumnByColumnIdData = {
    body?: never;
    path: {
        columnId: string;
    };
    query?: never;
    url: '/cards/column/{columnId}';
};

export type GetCardsColumnByColumnIdResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        content: string;
        projectId: string;
        sprintId: string;
        columnId: string;
        position: number;
        complexity: '1' | '2' | '3' | '5' | '8' | '13';
        priority: 'low' | 'medium' | 'high' | 'critical';
        githubBranchName: string | null;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetCardsColumnByColumnIdResponse = GetCardsColumnByColumnIdResponses[keyof GetCardsColumnByColumnIdResponses];

export type GetCardsProjectByProjectIdData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/cards/project/{projectId}';
};

export type GetCardsProjectByProjectIdResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        content: string;
        projectId: string;
        sprintId: string;
        columnId: string;
        position: number;
        complexity: '1' | '2' | '3' | '5' | '8' | '13';
        priority: 'low' | 'medium' | 'high' | 'critical';
        githubBranchName: string | null;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetCardsProjectByProjectIdResponse = GetCardsProjectByProjectIdResponses[keyof GetCardsProjectByProjectIdResponses];

export type GetCardsSprintBySprintIdData = {
    body?: never;
    path: {
        sprintId: string;
    };
    query?: never;
    url: '/cards/sprint/{sprintId}';
};

export type GetCardsSprintBySprintIdResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        content: string;
        projectId: string;
        sprintId: string;
        columnId: string;
        position: number;
        complexity: '1' | '2' | '3' | '5' | '8' | '13';
        priority: 'low' | 'medium' | 'high' | 'critical';
        githubBranchName: string | null;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetCardsSprintBySprintIdResponse = GetCardsSprintBySprintIdResponses[keyof GetCardsSprintBySprintIdResponses];

export type PutCardsByCardIdMoveData = {
    body: {
        targetColumnId: string;
        newPosition: number;
    };
    path: {
        cardId: string;
    };
    query?: never;
    url: '/cards/{cardId}/move';
};

export type PutCardsByCardIdMoveResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        content: string;
        projectId: string;
        sprintId: string;
        columnId: string;
        position: number;
        complexity: '1' | '2' | '3' | '5' | '8' | '13';
        priority: 'low' | 'medium' | 'high' | 'critical';
        githubBranchName: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type PutCardsByCardIdMoveResponse = PutCardsByCardIdMoveResponses[keyof PutCardsByCardIdMoveResponses];

export type PostTagsData = {
    body: {
        name: string;
        projectId: string;
    };
    path?: never;
    query?: never;
    url: '/tags';
};

export type PostTagsResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        name: string;
        projectId: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostTagsResponse = PostTagsResponses[keyof PostTagsResponses];

export type DeleteTagsByTagIdData = {
    body?: never;
    path: {
        tagId: string;
    };
    query?: never;
    url: '/tags/{tagId}';
};

export type DeleteTagsByTagIdResponses = {
    /**
     * Default Response
     */
    204: null;
};

export type DeleteTagsByTagIdResponse = DeleteTagsByTagIdResponses[keyof DeleteTagsByTagIdResponses];

export type GetTagsByTagIdData = {
    body?: never;
    path: {
        tagId: string;
    };
    query?: never;
    url: '/tags/{tagId}';
};

export type GetTagsByTagIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        projectId: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetTagsByTagIdResponse = GetTagsByTagIdResponses[keyof GetTagsByTagIdResponses];

export type PutTagsByTagIdData = {
    body?: {
        name?: string;
    };
    path: {
        tagId: string;
    };
    query?: never;
    url: '/tags/{tagId}';
};

export type PutTagsByTagIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        projectId: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type PutTagsByTagIdResponse = PutTagsByTagIdResponses[keyof PutTagsByTagIdResponses];

export type GetTagsProjectByProjectIdData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/tags/project/{projectId}';
};

export type GetTagsProjectByProjectIdResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        projectId: string | null;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetTagsProjectByProjectIdResponse = GetTagsProjectByProjectIdResponses[keyof GetTagsProjectByProjectIdResponses];

export type GetTagsCardByCardIdData = {
    body?: never;
    path: {
        cardId: string;
    };
    query?: never;
    url: '/tags/card/{cardId}';
};

export type GetTagsCardByCardIdResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        projectId: string | null;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetTagsCardByCardIdResponse = GetTagsCardByCardIdResponses[keyof GetTagsCardByCardIdResponses];

export type PostTagsAssignData = {
    body: {
        tagId: string;
        cardId: string;
    };
    path?: never;
    query?: never;
    url: '/tags/assign';
};

export type PostTagsAssignResponses = {
    /**
     * Default Response
     */
    204: null;
};

export type PostTagsAssignResponse = PostTagsAssignResponses[keyof PostTagsAssignResponses];

export type DeleteTagsByTagIdCardByCardIdData = {
    body?: never;
    path: {
        tagId: string;
        cardId: string;
    };
    query?: never;
    url: '/tags/{tagId}/card/{cardId}';
};

export type DeleteTagsByTagIdCardByCardIdResponses = {
    /**
     * Default Response
     */
    204: null;
};

export type DeleteTagsByTagIdCardByCardIdResponse = DeleteTagsByTagIdCardByCardIdResponses[keyof DeleteTagsByTagIdCardByCardIdResponses];
